### ISSUE TITLE
Feature request: support for some extremely common macOS keyboard shortcuts

### ISSUE THREAD

**Issue by joshlewis** [resin-io/etcher#1909] opened 2017-12-07 16:19 UTC
There are a handful of universal commands on macOS that your app should support, to feel right to an experienced Mac user. I'd recommend supporting these in your app:

⌘-H  -  Hide the app  (Command-H)
⌥⌘-H  -  Hide all other apps (Option-Command-H)
⌘,  -  Open preferences (Command-comma)

Since the app could support those features, it would be nice if it did. They're standard on all Mac apps.  You'll notice that other 3rd party apps often support all three, e.g. Chrome.

**Comment by lurch** [comment] 2017-12-07 16:21
Is this related to #1888 @jhermsmeier ?

**Comment by jhermsmeier** [comment] 2017-12-07 16:23
Yes, this will be fixed by #1888 
Duplicate of #1883

**Comment by jhermsmeier** [comment] 2017-12-07 16:23
Duplicate of #1883

**Closed** 2017-12-07 16:23 UTC
Labels: resolution:duplicate

**Comment by joshlewis** [comment] 2017-12-07 16:28
I don't see any mention of the ⌘,  preferences shortcut on any of those. Maybe this issue could be preserved to track that feature?

**Comment by lurch** [comment] 2017-12-07 16:32
@joshlewis I've added an extra comment to #1883 ... :-)

**Comment by joshlewis** [comment] 2017-12-07 16:38
Awesome! Thank you. 🙇

**Comment by jhermsmeier** [comment] 2017-12-07 16:44
Oh sorry, I missed that – totally should add that as well, thanks @joshlewis!

**Comment by jhermsmeier** [comment] 2018-01-05 22:06
Fixed by https://github.com/resin-io/etcher/pull/1888, released in v1.3.0
