### ISSUE TITLE
Feature request: Create an image from flashed device

### ISSUE THREAD

**Issue by fabiocody** [resin-io/etcher#2015] opened 2018-02-04 16:21 UTC
- **Etcher version**: 1.3.1
- **Operating system and architecture**: macOS 10.13.3

As the title suggests, it would be great to have the possibility to create an image from a flashed device.

**Comment by lurch** [comment] 2018-02-04 16:28
Duplicate of #266  :-)

**Closed by lurch** 2018-02-04 16:28 UTC
Labels: resolution:duplicate
