### ISSUE TITLE
[feature] Allow download of specific ISOs 

### ISSUE THREAD

**Issue by ShalokShalom** [resin-io/etcher#1462] opened 2017-05-20 11:54 UTC
I think, it makes the job for newbies easier, when we implement the function to recompile Etcher with a download link, so the distributions can create installers who create a live device based on one single app.

**Comment by lurch** [comment] 2017-05-20 13:01
This is a feature we've already got planned for [Etcher V2](https://resin.io/blog/the-future-of-etcher/) :-)

Closing this as a duplicate of #762

**Closed by lurch** 2017-05-20 13:01 UTC
Labels: resolution:duplicate

**Comment by ShalokShalom** [comment] 2017-08-12 20:30
@lurch This https://github.com/resin-io/etcher/issues/762 is closed, how to work on it?
Can you reopen it? Thanks

**Comment by lurch** [comment] 2017-08-14 10:04
Easiest option will be to just wait for Etcher V2, as this is something we won't be adding to Etcher V1.
Or you could create your own fork...

**Comment by ShalokShalom** [comment] 2017-08-14 10:20
I am waiting for V2. The question is, why this is closed? I mean, where does it get tracked?

**Comment by lurch** [comment] 2017-08-14 10:58
In our internal (private) Etcher V2 design documents...

**Comment by ShalokShalom** [comment] 2017-08-14 18:47
Ah i see.
