### ISSUE TITLE
Write from drive to and .img

### ISSUE THREAD

**Issue by Orrison** [resin-io/etcher#2428] opened 2018-07-31 22:58 UTC
- Etcher version: 1.4.4 (1.4.4)
- Operating system and architecture: MacOS High Serria

I was wondering if it is possible to write FROM a drive to an image.

I have used similar tools with this functionality in the past to make backups of a raspberryPi OS for use as a backup.

Is this something that is possible or planned for in the future?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e91f)

**Comment by lurch** [comment] 2018-08-01 10:00
Duplicate of #266 ?

**Closed** 2018-10-15 13:58 UTC
Labels: type:support
