### ISSUE TITLE
using etcher on debian linux for backup

### ISSUE THREAD

**Issue by 9jobsworth** [resin-io/etcher#1763] opened 2017-10-10 23:00 UTC
- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

i am using etcher as a replacement for the dangerous dd to flash micro sd cards for a raspberry pi.
i also use dd for backup to copy an image of a  micro sd card to a file on my pc.
i don't think that etcher can do this or can it?
thank you for etcher
best wishes
john

**Comment by Shou** [comment] 2017-10-12 10:21
Currently Etcher can't backup drives, however we have an issue if you want to track progress on this feature request:

Duplicate of https://github.com/resin-io/etcher/issues/266

**Closed by Shou** 2017-10-12 10:21 UTC
