### ISSUE TITLE
SSL Issue when booting up

### ISSUE THREAD

**Issue by eveaide** [resin-io/etcher#1700] opened 2017-08-19 19:39 UTC
- **Etcher version:1.1.2**
- **Operating system and architecture:Win10 Insider Preview Version 1703 (Build 16257.1) x64**
- **Image flashed:N/A**
- **Do you see any meaningful error information in the DevTools**
![image](https://user-images.githubusercontent.com/14147813/29489666-3b27580e-851e-11e7-8077-426592c5c06b.png)

I can gather it's some form of SSL issue, same happens on Portable and Installed. When booting, these error messages come up;
![image](https://user-images.githubusercontent.com/14147813/29489683-842b7ada-851e-11e7-94de-93f33081a83a.png)
![image](https://user-images.githubusercontent.com/14147813/29489684-90236e42-851e-11e7-84e0-b5797c4a3d50.png)

**Comment by lurch** [comment] 2017-08-20 09:39
It looks like you're actually running into two separate problems here - the first is that Etcher couldn't scan your drives, and then when Etcher tried to report that error back to our reporting service, you then ran into the second SSL-related error.

Are you using BitLocker? Maybe the first problem is a duplicate of #1687 ?

**Comment by eveaide** [comment] 2017-08-20 12:13
No Bitlocker, but I may have resolved this anyway. After shutting down "360 Total Security", it runs fine now. They must of updated some blacklist rules on their end, as it used to work fine before with both Etcher and 360TS.

**Comment by jviotti** [comment] 2017-08-21 21:39
@eveaide Are both issues solved when you shut down 360 Total Security? Can you actively reproduce by starting the software again?

**Comment by lurch** [comment] 2017-08-21 23:28
@jviotti I suspect that whatever @eveaide did to fix the "Couldn't scan drives" error (perhaps that was indeed turning off "360 Total Security") also meant that there was then no error message to report to our reporting service, and thus we have no way of knowing if that also fixes the SSL error or not ;-)

**Comment by lurch** [comment] 2018-02-28 15:11
@eveaide Are you still experiencing these problems with Etcher 1.3.1 ?

**Closed** 2018-10-15 13:00 UTC
Labels: component:analytics, component:drive detection, platform:windows, type:bug
