### ISSUE TITLE
can etcher be used to copy the image to a blank dvd-r disc

### ISSUE THREAD

**Issue by linuxfartbox** [resin-io/etcher#2432] opened 2018-08-02 12:34 UTC
- **Etcher version:**  version (1.4.4) 
- **Operating system and architecture:** Linux Mint 18.3 Sylvia Mate,  x86_64 GNU/Linux
- **Image flashed:** kali-linux-mate-2018.2-amd64.iso
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment] 2018-08-02 12:40
Nope, that needs dedicated DVD-writing software. Etcher can only write to block-devices (USB sticks, HDDs, SD cards, etc.)

**Comment by jhermsmeier** [comment] 2018-08-02 12:40
Duplicate of https://github.com/resin-io/etcher/issues/2086

**Closed** 2018-08-02 12:41 UTC
Labels: resolution:duplicate

**Comment by linuxfartbox** [comment] 2018-08-02 12:43
thanks
