### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ridzuanhs** [resin-io/etcher#1314] opened 2017-04-17 07:02 UTC
- **Etcher version:** Etcher-1.0.0-rc.3
- **Operating system and architecture:** Window 7 & 8.1
- **Do you see any meaningful error information on DevTools?** Command failed: Temp\1846.tmp.bat(code1)
Error command failed:
at childprocess.exithandler

**Comment by jviotti** [comment] 2017-04-17 15:29
Hi @ridzuanhs ,

Thanks a lot for reporting. This is a weird issue we've been tracking for a while, however the causes still remain unknown.

I'll close this issue in favour of https://github.com/resin-io/etcher/issues/1054, so lets continue discussion there. Do you mind taking a look at that thread, and see if you can provide any valuable info for us to fix?

Thanks a lot!

**Closed by jviotti** 2017-04-17 15:29 UTC
