### ISSUE TITLE
YAMLException when drive contains a new line character in its description

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1325] opened 2017-04-19 14:56 UTC
For example: `description: "foo\nbar"`

This scenario results in:

```
YAMLException: unexpected end of the stream within a double quoted scalar at line 3, column 1:
```

**Comment by lurch** [comment] 2017-04-20 14:30
Is this an Etcher error, or is it drivelist simply not handling YAML correctly?

**Comment by jviotti** [comment] 2017-04-20 14:46
The issue is that if a drive description contains a new line, like `description: "foo\nbar"`, it will be interpreted by the YAML parser as:

```
description: "foo
bar"
```

Which is invalid YAML.

**Comment by lurch** [comment] 2017-04-20 15:55
...in which case surely the problem is that we're giving mal-formed data to the YAML parser, rather than automatically stripping out all newlines? :)

**Comment by jviotti** [comment] 2017-04-20 16:02
Yep, exactly. We can strip down the new lines from the platform scripts before they get to the YAML parser.

**Comment by lurch** [comment] 2017-04-20 16:03
That's not _quite_ what I was suggesting, but never mind... ;-)

**Comment by jviotti** [comment] 2017-04-20 16:05
lol, what is the suggestion?

**Comment by lurch** [comment] 2017-04-20 16:06
Just edited my comment ;)

**Comment by jviotti** [comment] 2017-04-20 19:39
Sounds reasonable. We could play around with YAML multi line string (http://stackoverflow.com/a/21699210), which mainly rely on indentation, by dividing the whole thing by new lines, and checking strings that are not valid YAML, and indenting them.

**Comment by lurch** [comment] 2017-04-21 09:02
We're already using double-quoted strings, so perhaps the fix is to simply escape `\n`, `\t` etc. to `\\n` and `\\t`?  I wonder if https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/raw or https://www.npmjs.com/package/js-string-escape might be of any use here?

**Comment by lurch** [comment] 2018-02-26 15:43
See also https://github.com/resin-io-modules/drivelist/pull/156 and https://github.com/resin-io-modules/drivelist/pull/161

I guess the fact that this hasn't been fixed yet, illustrates exactly how often we come across drive-names that contain embedded newline characters ;-)

**Comment by jhermsmeier** [comment] 2018-04-06 20:31
This is fixed on Windows (by https://github.com/resin-io-modules/drivelist/pull/178) & Mac OS (by https://github.com/resin-io-modules/drivelist/pull/253), and will be fixed on Linux by https://github.com/resin-io-modules/drivelist/pull/255

**Comment by lurch** [comment] 2018-04-07 07:57
It was _already_ fixed on Linux by https://github.com/resin-io-modules/drivelist/pull/156 :wink:

**Closed** 2018-10-15 12:50 UTC
Labels: component:drive detection, platform:all, type:bug
