### ISSUE TITLE
Improve visual feedback on element :focus

### ISSUE THREAD

**Issue by Shou** [resin-io/etcher#860] opened 2016-11-10 13:44 UTC
Navigation using the tab key is tough because visual feedback is either too subtle or nonexistent when an element gains `:focus`, e.g. the "Select image" button, or warning dialog button(s).

**Comment by jviotti** [comment] 2016-11-11 07:33
Pinging @taahirisaacs and @konmouz for input on visual feedback.

**Comment by jhermsmeier** [comment] 2017-10-24 19:49
This is happening in https://github.com/resin-io/etcher/pull/1745

**Comment by lurch** [comment] 2018-02-26 13:03
Closing as duplicate of #1734

**Closed by lurch** 2018-02-26 13:03 UTC
Labels: component:gui, platform:all, status:pending design, type:ux
