### ISSUE TITLE
Allow inserting entropy to images

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1099] opened 2017-02-12 22:18 UTC
> because images are cloned, they all start with the same entropy, which means you can have an attack where you can somewhat-predict the pseudo-random generator if on boot the device hasn't had enough time to gather entropy

We can do it by populating `/var/lib/systemd/random-seed` (at least in the case of systemd images): https://www.freedesktop.org/software/systemd/man/systemd-random-seed.service.html

From https://github.com/resin-io/reconfix/issues/8

**Comment by lurch** [comment] 2018-02-26 14:07
Closing as a duplicate of #718

**Closed by lurch** 2018-02-26 14:07 UTC
Labels: component:writer, platform:all, type:feature
