### ISSUE TITLE
Add a cancel button the UI

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#2245] opened 2018-04-23 17:56 UTC
This will allow the user to cancel all flashes (for now), and potentially particular ones in the future.

**Comment by jviotti** [comment] 2018-04-23 17:56
This is blocked by https://github.com/resin-io/etcher/issues/2234

**Comment by jviotti** [comment] 2018-04-23 17:56
We also need some designs from @konmouz

**Comment by lurch** [comment] 2018-04-23 23:03
Duplicate of #1791 ?

**Comment by jviotti** [comment] 2018-04-26 17:03
![screen 03-02](https://user-images.githubusercontent.com/2192773/39320474-3c398d04-4952-11e8-91cb-b1fc81eb3dff.png)

**Comment by jviotti** [comment] 2018-04-26 17:04
We should also add a modal that says "Are you sure you want to cancel?" or something like that

**Closed** 2018-05-03 09:58 UTC
Labels: component:gui, priority:low

**Comment by konmouz** [comment] 2019-06-26 11:49
<img width="1210" alt="Screenshot 2019-06-26 at 12 49 22" src="https://user-images.githubusercontent.com/15323961/60177452-d7447f80-9810-11e9-8735-d59d34a6f649.png">

Updated design - https://zpl.io/aRzJezg
