### ISSUE TITLE
Couldn't scan the drives: An unknown error occurred

### ISSUE THREAD

**Issue by maxgrass** [resin-io/etcher#1665] opened 2017-08-03 16:28 UTC
- **Etcher version: 1.1.1**
- **Operating system and architecture: Win10 x64**
- **Image flashed: --**
- **Do you see any meaningful error information in the DevTools?**

![image](https://user-images.githubusercontent.com/169885/28932029-676b1bba-7878-11e7-9adf-5bbf926c7301.png)

![image](https://user-images.githubusercontent.com/169885/28932279-33e2a2d0-7879-11e7-955a-82e984f0bf08.png)

![image](https://user-images.githubusercontent.com/169885/28932337-6d6e8d48-7879-11e7-92d6-508be18b7fae.png)

The error comes right away after the start. (no img selection)
There is a SD card in the slot.
Tried running as Admin as well.

{"stack":"Error: Couldn't scan the drives: An unknown error occurred","message":"Couldn't scan the drives: An unknown error occurred"}

Everything works with version 1.0.0

Tried with both "-portable" and installer version.

**Comment by lurch** [comment] 2017-08-03 16:33
Duplicate of #1646

**Comment by jviotti** [comment] 2017-08-03 16:34
@lurch Do you think we should post links to the snapshot builds here?

**Closed** 2017-08-03 16:33 UTC
Labels: resolution:duplicate

**Comment by lurch** [comment] 2017-08-03 16:36
Good call :)   (I wasn't sure how soon you were planning on releasing 1.1.2, given that this bug seems to be affecting multiple people?)

**Comment by jviotti** [comment] 2017-08-03 16:41
I was planning to release today/tomorrow, but I rather do it on Monday, to avoid having to spend my weekend hot fixing stuff :P

**Comment by jviotti** [comment] 2017-08-03 17:20
Can you try the following snapshot build that contains the fix: https://drive.google.com/file/d/0B7tkbonGU-RyTUNKaVpLb2VCZ1E/view?usp=sharing? If that still doesn't work, can you set the `DRIVELIST_DEBUG` environment variable and execute the application from `cmd.exe`, so you can see the debug logs?

For example:

```
set DRIVELIST_DEBUG=1
cd C:\Program Files\Etcher
etcher.exe
```

**Comment by maxgrass** [comment] 2017-08-03 17:30
It's working. Thank you.

**Comment by lurch** [comment] 2017-08-03 19:07
@jviotti Out of curiosity, how come you're linking to a snapshot build on google drive rather than one of the snapshot builds in our S3 bucket?

**Comment by jviotti** [comment] 2017-08-03 21:41
@maxgrass Thanks a lot for confirming this!

@lurch I accidentally broke snapshot builds in a previous commit. See https://github.com/resin-io/etcher/pull/1666

**Comment by mwsasser** [comment] 2017-08-04 14:20
The snapshot build is working for me as well, the release version was not.

**Comment by hadjilucasL** [comment] 2017-08-05 15:09
I suspect in my case it was failing to scan because I had a floppy disk drive attached to the system. The floppy drive appears as a disk path but it will error out if there is no disk in the drive. 

```
C:\>A:
The device is not ready.

C:\>
```

The snapshot build works but appears to continuously poll the drive for access until a drive is finally selected. 

Windows 10 x64, Floppy Drive at (A:)

**Comment by lurch** [comment] 2017-08-05 23:02
> I had a floppy disk drive attached to the system

Wow, old-skool :sunglasses: :wink: 

> appears to continuously poll the drive for access until a drive is finally selected.

Yeah, Etcher re-runs `drivelist` every two seconds, to take account for USB drives / SD cards / etc. being inserted and removed (unfortunately repeated polling is the only reliable cross-platform way to get this info). @jviotti @jhermsmeier I wonder if we added a user-configurable "delay betweeen drivelist-rescans" that'd make the Etcher experience less bad for @hadjilucasL ?

**Comment by jviotti** [comment] 2017-08-07 02:43
@lurch Recent changes cause drivelist to only poll X amount of seconds **after** the previous run completed, so that should be enough to mitigate these kinds of issues.

**Comment by drencorxeen** [comment] 2017-08-07 05:23
@maxgrass,  what you posted does work as a work around.

My question is shouldn't the application be able to run without setting this value in a command prompt?

@lurch ,

Wouldn't that be old school :P :)

**Comment by mwsasser** [comment] 2017-08-07 13:24
I wonder if the release version didn't like my WevDAV network mapped drives?

**Comment by jviotti** [comment] 2017-08-07 16:54
@drencorxeen 

> My question is shouldn't the application be able to run without setting this value in a command prompt?

The environment value I suggested above is just to get more debugging information in case the snapshot build didn't work.

**Comment by jviotti** [comment] 2017-08-07 16:55
@mwsasser Could be! The fix seems general enough to cover most cases. We basically check if we are not allowed to get the device number of a certain drive, and if so omit it.

**Comment by jviotti** [comment] 2017-08-08 13:53
Etcher v1.1.2 is available at https://github.com/resin-io/etcher/releases/tag/v1.1.2. Let me know how it goes!

**Comment by mubed** [comment] 2017-08-29 07:26
I still have this problem in Version 1.1.2 (Win7):
![2017-08-29 09_07_32-error](https://user-images.githubusercontent.com/694738/29809339-0fb1ad52-8c9c-11e7-9e21-da1b5fdbad37.png)
