### ISSUE TITLE
[Feature Request] - md5sum of the .img file

### ISSUE THREAD

**Issue by fus3d** [resin-io/etcher#1676] opened 2017-08-07 16:45 UTC
Would be great if there's an option to calculate the md5sum of .img file right within Etcher.

Then we don't need a separate utility to perform the md5sum calculation.

**Comment by lurch** [comment] 2017-08-08 09:46
Duplicate of #643  (but see also https://github.com/resin-io/etcher/issues/993#issuecomment-275706782 )

**Closed by lurch** 2017-08-08 09:46 UTC
Labels: resolution:duplicate
