### ISSUE TITLE
I have win10 and Etcher v1.4.4 runs in the background, no GUI

### ISSUE THREAD

**Issue by oznelig** [resin-io/etcher#2339] opened 2018-05-15 00:21 UTC
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by jhermsmeier** [comment] 2018-05-15 02:08
Duplicate of https://github.com/resin-io/etcher/issues/1866

**Closed by jhermsmeier** 2018-05-15 02:08 UTC
