### ISSUE TITLE
Windows ISO Support !

### ISSUE THREAD

**Issue by liberodark** [resin-io/etcher#1445] opened 2017-05-17 11:26 UTC
Hello,

Please add a windows iso support for linux.

Cordialy

**Comment by lurch** [comment] 2017-05-17 12:05
Duplicate of #210

**Closed by lurch** 2017-05-17 12:05 UTC
Labels: component:writer, platform:all, type:feature

**Comment by nomanrk** [comment] 2017-07-22 02:34
Agree! 
Just tried to burn Win 10 iso file on USB through Etcher, and it denied.
