### ISSUE TITLE
Etcher 1.4.4 does not run on Ubuntu budgie 18.04 minimal 64bit 

### ISSUE THREAD

**Issue by Der-Bauer** [resin-io/etcher#2359] opened 2018-05-20 14:09 UTC
- **Etcher version:1.4.4** 
- **Operating system and architecture:Ubuntu Budgie 18.04 minimal 64Bit** 
- **Image flashed:none** 
- **Do you see any meaningful error information in the DevTools?** 
      First i got problems to intergrated etcher to my menu after resolved this.I want to  start ether and 
     seems it´s  running but some seconds later it closed its self

**Comment by lurch** [comment] 2018-05-20 16:14
Duplicate of #1305 ?

**Comment by Der-Bauer** [comment] 2018-05-20 17:42
It is
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 20.05.18, 18:14, Andrew Scheller <notifications@github.com> schrieb:
Duplicate of #1305 ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/resin-io/etcher/issues/2359#issuecomment-390493275","url":"https://github.com/resin-io/etcher/issues/2359#issuecomment-390493275","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/resin-io/etcher","title":"resin-io/etcher","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/resin-io/etcher"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lurch in #2359: Duplicate of #1305 ?"}],"action":{"name":"View Issue","url":"https://github.com/resin-io/etcher/issues/2359#issuecomment-390493275"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [resin-io/etcher] Etcher 1.4.4 does not run on Ubuntu budgie 18.04 minimal 64bit  (#2359)",
"sections": [
{
"text": "",
"activityTitle": "**Andrew Scheller**",
"activityImage": "https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png",
"activitySubtitle": "@lurch",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"resin-io/etcher\",\n\"issueId\": 2359,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"resin-io/etcher\",\n\"issueId\": 2359\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/resin-io/etcher/issues/2359#issuecomment-390493275"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 337140153\n}"
}
],
"themeColor": "26292E"
}

**Comment by lurch** [comment] 2018-06-05 13:59
@jhermsmeier This can be closed as a duplicate.

**Comment by jhermsmeier** [comment] 2018-06-05 14:30
Duplicate of #1305

**Closed by jhermsmeier** 2018-06-05 14:30 UTC
Labels: resolution:duplicate
