### ISSUE TITLE
Possibility to flash only a partition on a multiple partitionated USB

### ISSUE THREAD

**Issue by mymike00** [resin-io/etcher#1524] opened 2017-06-16 07:58 UTC
I have a USB with 2 partition: I want to use one for my stuffs and the other for a LinuxLiveUSB. I like Etcher and I prefer it instead of other softwares, but I can't install an OS only on a partition: Etcher formats all my USB installing the OS on a whole partition. It would be very usefull if I can choose on which partition install the OS (without erease datas from the other, of course ^^)

**Comment by jviotti** [comment] 2017-06-16 21:25
Hi @mymike00 ,

Keep in mind that Etcher does **not** partition the drive. As an image flasher, the only thing it does is copy an image to a drive byte by byte, without any transformation. Images contain their own partition table, which means that allowing users to flash an image that comes with multiple partitions to a single partition requires non-trivial transformations and intimate knowledge of what the image represents (e.g. we should hardcode logic for certain Linux distros, etc)

Closing as a duplicate of https://github.com/resin-io/etcher/issues/453.

**Closed by jviotti** 2017-06-16 21:25 UTC
