### ISSUE TITLE
Please can you add "persistent" option ?

### ISSUE THREAD

**Issue by Nokia808** [resin-io/etcher#1309] opened 2017-04-15 18:27 UTC
- **Etcher version:** 1.0 beta 19
- **Operating system and architecture:** Fedora Linux 24 Cinnamon edition
- **Do you see any meaningful error information on DevTools?**

Hi. 1st I would to say thank you very much for your very hard efforts to make this great useful application.
I noticed that there is no option for "persistent". 

- Ubuntu & Ubuntu derivatives have an option "persistent". 

- Also Debian & Debian derivatives can add to them "persistent" though it is more complicated (not simple as Ubuntu)

**Comment by jviotti** [comment] 2017-04-15 19:15
Hey there!

Thanks for reporting. This is a duplicate of https://github.com/resin-io/etcher/issues/413, so lets continue discussion over there.

**Closed by jviotti** 2017-04-15 19:15 UTC
