### ISSUE TITLE
tv

### ISSUE THREAD

**Issue by jbubriski** [resin-io/etcher#2463] opened 2018-09-02 00:13 UTC
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by jhermsmeier** [comment] 2018-09-02 11:53
I suspect that this was opened accidentally, and hence closing - if that's not the case, please do reopen it, and it'd also be great if you could provide some more information as to what the issue is.

**Closed by jhermsmeier** 2018-09-02 11:53 UTC
