### ISSUE TITLE
Creating a disk image

### ISSUE THREAD

**Issue by zhiwan** [resin-io/etcher#1063] opened 2017-01-30 19:32 UTC
- **Etcher version:** 1.0.0-beta18
- **Operating system and architecture:** Mac OS Sierra
- **Do you see any meaningful error information on DevTools?**

This tool is quick amazing and would like to thank everyone who contributed. I've had to use win32diskimage for most of my image burning and this alternative is quite compelling. One thing I was wondering is if ether will create a disk image from an existing source? I couldn't find any information about this. Thanks!

**Comment by lurch** [comment] 2017-01-30 19:43
Duplicate of #266

**Closed by lurch** 2017-01-30 19:43 UTC
