### ISSUE TITLE
Error message when trying to add zip file

### ISSUE THREAD

**Issue by Murphyv310** [resin-io/etcher#2399] opened 2018-06-19 12:30 UTC
![screenshot from 2018-06-19 13-21-06](https://user-images.githubusercontent.com/34967905/41597321-107dfd74-73c5-11e8-94c3-fdf37dc3319c.png)
- **Etcher version:** 1.43x86_64
- **Operating system and architecture:** Linux Mint 18.3 Cinnamon 64 bit
- **Image flashed:** Noobs V2_8_1.zip
- **Do you see any meaningful error information in the DevTools?** 

I get this error, it has worked OK in the past but new downloads seem to be more problematical, same issue on another PC using the Mint 18.3 but 32 bit 

/home/trevor/Pictures/Screenshot from 2018-06-19 13-21-06.png

**Comment by jhermsmeier** [comment] 2018-06-19 14:00
NOOBS is not a disk image (and hence Etcher can't flash it), but an archive of a boot partition; please see #1756 for some background, and refer to the [Raspberry Pi Foundation's documentation](https://www.raspberrypi.org/documentation/installation/noobs.md).

Duplicate of https://github.com/resin-io/etcher/issues/1162

**Comment by jhermsmeier** [comment] 2018-06-19 14:00
Duplicate of https://github.com/resin-io/etcher/issues/1162

**Closed by jhermsmeier** 2018-06-19 14:00 UTC
Labels: type:support

**Comment by Murphyv310** [comment] 2018-06-19 18:59
I see,  thanks for the explanation. 
Back to the drawing board.

**Comment by jhermsmeier** [comment] 2018-06-19 19:04
@Murphyv310 you can flash the other Raspbian images with Etcher though, unless you need / want to use NOOBS

**Comment by Murphyv310** [comment] 2018-06-19 21:15
Thank you.
I've a 3b+ and I've found out that Ubuntu Mate doesn't load, my previous 3B was OK. To be honest all I want to run is GQRX  and other SDR software but the 3B+ doesn't play ball,  feeling like giving up on the Pi now.

**Comment by lurch** [comment] 2018-06-20 10:20
> I've a 3b+ and I've found out that Ubuntu Mate doesn't load, my previous 3B was OK.

I've not used Ubuntu Mate on the RPi myself, but the 3B+ needs newer firmware blobs than the 3B. I did a quick search and there seems to be multiple topics about the 3B+ at https://ubuntu-mate.community/c/support/raspberry-pi-2
