### ISSUE TITLE
Clone SD Card

### ISSUE THREAD

**Issue by sp2ong** [resin-io/etcher#1733] opened 2017-09-18 07:18 UTC
Hi,

It will be nice to have option in ETHER to create CLONE / BACKUP image from sd card to disk

Regards

**Comment by jhermsmeier** [comment] 2017-09-18 09:11
Hi, this is already being worked on, see #266 for details

**Comment by jhermsmeier** [comment] 2017-09-18 09:11
Duplicate of #266

**Closed by jhermsmeier** 2017-09-18 09:11 UTC
