### ISSUE TITLE
Support invoke with image file name as command line parameter

### ISSUE THREAD

**Issue by kraml** [resin-io/etcher#1740] opened 2017-09-23 11:45 UTC
- **Etcher version:**
1.1.2

- **Operating system and architecture:**
Windows x64

- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

Could you make Etcher accept a command line parameter and use it as the image file name, instead of have to open and select it every time?

I'm using Total Commander and it allows to a create toolbar button for any program. I usually create a button when clicked it can pass the current file name under cursor to a program. If that program supports receiving a file name as command line parameter then it is very convenient to be used in such manner. I'm doing this for many programs such as editors, media players etc.. It will be great if Etcher could also support it.

**Comment by lurch** [comment] 2017-09-23 12:41
Closing this as a duplicate of #1386 (slightly different question, but they both need the same change).

**Closed** 2017-10-03 09:16 UTC
Labels: resolution:duplicate
