### ISSUE TITLE
Remaining perl process on MacOS

### ISSUE THREAD

**Issue by damiencaselli** [resin-io/etcher#1421] opened 2017-05-12 14:50 UTC
- **Etcher version: v1.0.0**
- **Operating system and architecture: MacOS 10.12.4**

After quitting Etcher, I noticed a `perl` process remains and seems to drain CPU like crazy. I thought that wasn't related to Etcher in any way, but inspecting the process proved me wrong.

![screen shot 2017-05-12 at 4 29 12 pm](https://cloud.githubusercontent.com/assets/37416/26003236/687990a4-3732-11e7-9839-bf145ab25581.png)

I have no idea what triggers this, but flashing image went right, and no error was reported at any moment.

Sorry if this is an Electron related issue, but I couldn't find anything related to perl on their repository either.

**Comment by lurch** [comment] 2017-05-12 14:54
Yeah, duplicate of #1288 and we've no idea yet what causes this :-S
Please feel free to add any extra comments you might have to that other issue.

**Closed by lurch** 2017-05-12 14:54 UTC
