### ISSUE TITLE
Feature Request: Confirm Flash

### ISSUE THREAD

**Issue by Phoenix1747** [resin-io/etcher#2005] opened 2018-01-29 10:29 UTC
- **Etcher version: 1.3.1**
- **Operating system and architecture: Windows 8.1 64-bit**
- **Image flashed: Manjaro Architect 64-bit**
- **Do you see any meaningful error information on DevTools?**

It would be really helpful to ask the user for confirmation before flashing with like the info about what image and where it is going to flash it. Would help to resolve some struggles (and also issue #983, which looks solved but whatever) especially if you didn't look after where the image is going and then accidentally overwrite 900GB of data on an hard disk like I did, lol.

**Comment by lurch** [comment] 2018-01-29 16:34
Thanks for the suggestion, but IMHO if we added too many pop-up confirmation dialogs, then users would just get annoyed by them, and ignore what they say anyway.
The info about what image is being written, and which drive it's being written to, **is** always visible in the Etcher interface.

I'm going to close this as a duplicate of #1916

**Closed by lurch** 2018-01-29 16:34 UTC
