### ISSUE TITLE
Visual - More info on file and device selected (too much truncated)

### ISSUE THREAD

**Issue by privacy-wolf** [resin-io/etcher#1845] opened 2017-11-15 07:23 UTC
Information about which iso-file and which usb-device was actually selected is quite important - the information in the Etcher screen is rather short (truncated) which makes it sometimes hard to read/recognize it - although there would be enough space to provide more information.

I would suggest to move the size information (for filename and device) on a separate line just below the file and device name thus giving more space for longer names (cf. screenshot below).

![etcher screenshot](https://user-images.githubusercontent.com/26414712/32823564-f29ba7de-c9dd-11e7-95be-b6322f7bf0fd.gif)

**Comment by lurch** [comment] 2017-11-15 15:13
If you mouse-hover over the truncated names you can see more info - is that what you're looking for?
We try very hard to keep the Etcher GUI as "clean" and as user-friendly as possible, without bombarding the user with information that they may not need.

**Comment by alexandrosm** [comment] 2017-11-20 03:05
@lurch I think we can afford to put the size on the next line though. @konmouz what do you think?

**Comment by konmouz** [comment] 2017-11-20 11:50
@lurch @alexandrosm, we can do that, the only small issue is that we also have the 'change' CTA underneath. To avoid making it look like 3 lines of text, we could give a good amount of vertical space (e.g. 2 lines) between 'image size' and 'change'

**Comment by alexandrosm** [comment] 2017-11-23 01:40
worth trying

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by lurch** [comment] 2018-02-28 15:33
Duplicate of #1292

**Closed by lurch** 2018-02-28 15:33 UTC
Labels: component:gui, platform:all, type:ux
