### ISSUE TITLE
ETA is wrongly calculated for compressed image

### ISSUE THREAD

**Issue by j123b567** [resin-io/etcher#2410] opened 2018-07-02 10:26 UTC
- **Etcher version:** 1.4.4
- **Operating system and architecture:** Linux 4.14.4 x86_64 Gentoo
- **Image flashed:** custom compressed image
- **Do you see any meaningful error information in the DevTools?** no

I have compressed custom image for RPi CM3 `custom.img.gz` not publicly available
- size of compressed image 509237724 B (509 MB)
- size of uncompressed image 3909091328 B (3.9 GB)
- speed of writing - stable around 5.5 MB/s
- ETA started at around 1m30s and goes slowly to 0. ETA should start at around 12m and it should go 1s per second.

Maybe it is related to #1908

**Comment by jhermsmeier** [comment] 2018-07-02 12:43
Yeah, somewhat a duplicate of that. Gzip doesn't have a reliable uncompressed size field, so there's no way for Etcher to know the uncompressed size before flashing, and hence the ETA is estimated based on the amount of compressed data read.

Closing this, as there are other issues open regarding this, and it's also a "cantfix" due to how the gzip compression scheme works.

**Closed by jhermsmeier** 2018-07-02 12:43 UTC
