### ISSUE TITLE
Error trying to burn Linux Mint

### ISSUE THREAD

**Issue by 82lbpizza** [resin-io/etcher#2340] opened 2018-05-15 02:13 UTC
- **Etcher version:** 1.4.4
- **Operating system and architecture:** Windows 10 Education
- **Image flashed:** linuxmint 18.3 cinnamon 64bit
- **Do you see any meaningful error information in the DevTools?** 
![image](https://user-images.githubusercontent.com/39286913/40032848-cd5aad66-57c3-11e8-83a3-d4225fb58f96.png)

The error listed in the devtool looks the same as the one on the popup that came up.

Any ideas?  If there's more info I can give let me know!

**Comment by lurch** [comment] 2018-05-15 08:14
Duplicate of #1793 ?

**Comment by jhermsmeier** [comment] 2018-05-15 09:35
Yup

**Closed by jhermsmeier** 2018-05-15 09:35 UTC
Labels: resolution:duplicate
