### ISSUE TITLE
GPG key broken for .deb package installation

### ISSUE THREAD

**Issue by joelgraff** [resin-io/etcher#2317] opened 2018-05-09 11:26 UTC
Running Pop!_OS (Bionic), I tried to install etcher.io using the debian package.  Following the instructions in the README failed on step 2 (trusting the GPG key).  Output:

Executing: /tmp/apt-key-gpghome.3jIOEArhfW/gpg.1.sh --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
gpg: keyserver receive failed: No data

**Comment by jhermsmeier** [comment] 2018-05-09 11:38
Duplicate of #1786

**Closed** 2018-05-09 15:36 UTC
Labels: resolution:duplicate, type:support
