### ISSUE TITLE
Debian/Ubuntu Repository Release file has no entry for amd64

### ISSUE THREAD

**Issue by aloisklink** [resin-io/etcher#1633] opened 2017-07-26 09:46 UTC
Firstly, thanks for making this program, I write OS images to SD cards all the time, and etcher makes it super easy to this!

I'm having an issue with running `sudo apt update`, and am getting the following error:

```
Ign:9 https://dl.bintray.com/resin-io/debian stable InRelease
Get:10 https://dl.bintray.com/resin-io/debian stable Release [435 B]
Get:12 https://dl.bintray.com/resin-io/debian stable Release.gpg [821 B]
E: Failed to fetch https://dl.bintray.com/resin-io/debian/dists/stable/InRelease  Unable to find expected entry 'etcher/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I looked at the repository Release file at https://dl.bintray.com/resin-io/debian/dists/stable/Release and it seems to me it should have `Architecture: i386, amd64` and hash check-sums for `etcher/binary-amd64/Packages`, since at https://dl.bintray.com/resin-io/debian/dists/stable/etcher/binary-amd64/ there are amd64 packages.

```
Origin: Bintray
Label: Bintray
Suite: stable
Codename: stable
Date: Tue, 25 Jul 2017 17:03:28 UTC
Components: etcher
Architecture: i386
MD5Sum:
 5cfe7511c35b3b6738fb41f4f82f36c9            15511 etcher/binary-i386/Packages
SHA1:
 9aa1067f8bb60f5d061f285a952032b12a20c5ed            15511 etcher/binary-i386/Packages
SHA256:
 a0c7ef6b6ebe64a2be73568b9cb84b6222015092fadc785c9bde4910ebe14538            15511 etcher/binary-i386/Packages
```

I have etcher-electron 1.1.0 through `apt`, so it must have worked then, but not version 1.1.1

**Comment by lurch** [comment] 2017-07-26 14:55
Duplicate of #1634

**Closed by lurch** 2017-07-26 14:55 UTC
