### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by vendforce** [resin-io/etcher#1478] opened 2017-05-27 19:01 UTC
- **Etcher version:** 1.0.0
- **Operating system and architecture:** windows 7 x64
- **Image flashed:** n/a
- **Do you see any meaningful error information in the DevTools?** no

Will etcher ever have support to burn an windows iso image

**Comment by jviotti** [comment] 2017-05-28 02:31
Hi @vendforce ,

Thanks for reaching out. Adding Windows support is not a priority for the time being, given that the main focus on Etcher is on IoT devices rather than desktop OSes. I know @jhermsmeier has been experimenting with Windows images at some point, but keep in mind that we're not allocating any resources for this. 

That being said, if you find out how to correctly flash Windows images in a cross platform way, I'd be happy to take a patch for it.

Closing this as a duplicate of https://github.com/resin-io/etcher/issues/210

**Closed by jviotti** 2017-05-28 02:31 UTC
