### ISSUE TITLE
Need a force (-f) or --unsafe in Etcher CLI

### ISSUE THREAD

**Issue by gbnyc26** [resin-io/etcher#1966] opened 2018-01-09 18:39 UTC
- **Etcher version:**: Etcher-cli-1.2.1-darwin-x64
- **Operating system and architecture:** macOS High Sierra 10.13.2
- **Image flashed:** No
- **Do you see any meaningful error information in the DevTools?**: Using CLI

Similar experience to https://github.com/resin-io/etcher/issues/1820, except on CLI.  Ran darwinish.sh for drive in question.

enumerator: diskutil
busType: UNKNOWN
busVersion: "0.0"
device: /dev/disk2
raw: /dev/rdisk2
description: "SD Card Reader"
error: null
size: 31914983424
blockSize: null
logicalBlockSize: null
mountpoints:
  - path: "/Volumes/boot"
isReadOnly: False
isSystem: False
isVirtual: null
isRemovable: null
isCard: null
isSCSI: null
isUSB: null
isUAS: null

#1820 highlights the need to operate in unsafe mode.

Can you please add this to the CLI?

Thanks!

**Comment by lurch** [comment] 2018-01-10 18:43
Duplicate of #1420

**Closed by lurch** 2018-01-10 18:43 UTC
