### ISSUE TITLE
Mixpanel tracking fires with disabled analytics

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher#1772] opened 2017-10-14 16:06 UTC
- **Etcher version:** v1.1.2
- **Operating system and architecture:** any
- **Image flashed:** any
- **Do you see any meaningful error information in the DevTools?**

![screen shot 2017-10-14 at 18 02 59](https://user-images.githubusercontent.com/244907/31577170-26b162c6-b10a-11e7-97c5-f1e244af70f0.png)

As can be seen here, two events are tracked and sent to Mixpanel at application startup, even though the analytics setting is disabled.

Connects To: #1770

**Comment by ValdikSS** [comment] 2017-11-25 18:42
Not fixed in 1.2.0.

**Comment by jviotti** [comment] 2017-11-26 16:21
Hi @ValdikSS ,

Thanks for reviving this thread. I thought we sent a fix for this ticket already, and that we simply forgot to close the issue with the corresponding PR. @jhermsmeier do you remember where I can find that PR?

@ValdikSS I gave this another go using the v1.2.0 on my Mac but couldn't reproduce the issue anymore. I disabled analytics, opened Etcher, and no request was sent to `api.mixpanel.com`:

<img width="1082" alt="screen shot 2017-11-26 at 12 17 56 pm" src="https://user-images.githubusercontent.com/2192773/33241982-2b68db4e-d2a4-11e7-995c-cbe17f51dcfb.png">

How are you analyzing this? Could it be that the DevTools Network monitor is not fast enough to log certain requests you found somewhere else? Let me know so we can track this down!

**Comment by jviotti** [comment] 2017-11-26 17:50
Thanks for the clarification @ValdikSS. I was able to get to the same conclusion by using WireShark. I sent an initial PR (https://github.com/resin-io/etcher/pull/1879/files) that ensures that local settings are loaded before bootstrapping the application, but looks like the Mixpanel library still sends some initial events during its own startup that we have to find a way to shutdown. This will probably need to be done in Corvus.

**Comment by jviotti** [comment] 2017-11-26 18:12
I fixed one last mysterious `/decide/` call from the Mixpanel library here: https://github.com/resin-io-modules/resin-corvus/pull/35

**Comment by jviotti** [comment] 2017-11-26 18:22
I fixed the last remaining edge case: https://github.com/resin-io-modules/resin-corvus/pull/36.

Thanks for the heads up @ValdikSS! I definitely wouldn't have noticed that this was still the case without a packet sniffer or by refreshing the application through DevTools. 

This fix will land in the next release (probably v1.2.1) very soon, and apologies for not allocating more time to properly fix this!

**Comment by ValdikSS** [comment] 2017-11-26 18:25
Great, thanks.

**Closed** 2017-12-05 15:04 UTC
Labels: component:analytics, important, platform:all, type:bug
