### ISSUE TITLE
Couldn't Initalise The Scanner: An Unknow Error Occurred

### ISSUE THREAD

**Issue by Modelmat** [resin-io/etcher#1660] opened 2017-08-03 06:31 UTC
- **1.1.1**
- **Win 10 Edu x64**
- **No meaningful error information in the DevTools**

Just this and then cannot find USB

**Comment by jhermsmeier** [comment] 2017-08-03 09:06
Duplicate of #1646

**Closed by jhermsmeier** 2017-08-03 09:06 UTC

**Comment by jhermsmeier** [comment] 2017-08-03 09:08
Do you have any virtual drives, virtual file systems or spinning HDDs attached to your system?

**Comment by Modelmat** [comment] 2017-08-03 09:10
I do not have any virtual drives, VFS and I do have a secondary HDD.

**Comment by jviotti** [comment] 2017-08-03 17:20
Can you try the following snapshot build that contains the fix: https://drive.google.com/file/d/0B7tkbonGU-RyTUNKaVpLb2VCZ1E/view?usp=sharing? If that still doesn't work, can you set the `DRIVELIST_DEBUG` environment variable and execute the application from `cmd.exe`, so you can see the debug logs?

For example:

```
set DRIVELIST_DEBUG=1
cd C:\Program Files\Etcher
etcher.exe
```
