### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fcailloux** [resin-io/etcher#1958] opened 2018-01-07 16:31 UTC
1.30
peppermint os
any image crash
buffer error

- **Etcher version:**
- **Operating system and architecture:**
- **Image flashed:**
- **Do you see any meaningful error information in the DevTools?**

**Comment by alexandrosm** [comment] 2018-01-07 19:46
Hi there, thanks for the report. We've rolled back the 1.3.0 release,
please re-download from the website until we can fix this issue.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jhermsmeier** [comment] 2018-01-08 15:25
@fcailloux can you give us more detail on the "buffer error"? Might this be a duplicate of #1955?

**Comment by lurch** [comment] 2018-02-28 16:10
Closing, as assuming this was fixed by the Etcher 1.3.1 release.
@fcailloux Please feel free to leave more details if you're still having problems with the latest version.

**Comment by jhermsmeier** [comment] 2018-02-28 17:35
Duplicate of https://github.com/resin-io/etcher/issues/1955

**Closed by jhermsmeier** 2018-02-28 17:35 UTC

**Comment by lurch** [comment] 2018-02-28 17:40
Whoops, guess I forgot to actually click the "Close" button :rofl:
