### ISSUE TITLE
Allow terminal other than xterm

### ISSUE THREAD

**Issue by act78723** [resin-io/etcher#554] opened 2016-07-02 16:41 UTC
- **What Etcher version are you running?**
1.0.0-beta.10 Etcher-linux-x64.AppImage

- **What operating system and architecture are you running Etcher in?**
LinuxMint (Mate x64) 17.3

- **What is the behaviour you're experiencing? How can we reproduce it?**

Details: Failed to execute child process "xterm" (No such file or directory)

  - [OS X](https://raw.githubusercontent.com/resin-io-modules/drivelist/master/scripts/darwin.sh)
  - [GNU/Linux](https://raw.githubusercontent.com/resin-io-modules/drivelist/master/scripts/l
(https://raw.githubusercontent.com/resin-io-modules/drivelist/master/scripts/linux.sh)
  - [Windows](https://raw.githubusercontent.com/resin-io-modules/drivelist/master/scripts/win32.bat)

**Comment by jviotti** [comment] 2016-07-04 13:15
Hi @act78723 ,

Thanks for reporting this! At which point does this error happen (e.g: when you run the AppImage, right after you click "Flash", etc)?

We're definitely not hardcoding a terminal name anywhere, so my guesses are either that the NodeJS Child Process module is picking `xterm` by default, or this comes from the AppImage runtime code.

**Comment by act78723** [comment] 2016-07-04 20:43
I believe it's coming from the NodeJS Child Process.

**Comment by jviotti** [comment] 2016-07-05 13:21
I'll give this a go on Ubuntu 16.04 after making sure `xterm` is removed
and see if I can reproduce.

On Mon, Jul 04, 2016 at 01:43:42PM -0700, act78723 wrote:
> I believe it's coming from the NodeJS Child Process.
> 
> On 07/04/2016 09:15 AM, Juan Cruz Viotti wrote:
> >
> > Hi @act78723 <https://github.com/act78723> ,
> >
> > Thanks for reporting this! At which point does this error happen (e.g: 
> > when you run the AppImage, right after you click "Flash", etc)?
> >
> > We're definitely not hardcoding a terminal name anywhere, so my 
> > guesses are either that the NodeJS Child Process module is picking 
> > |xterm| by default, or this comes from the AppImage runtime code.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub 
> > <https://github.com/resin-io/etcher/issues/554#issuecomment-230287973>, or 
> > mute the thread 
> > <https://github.com/notifications/unsubscribe/ARX8L551GCq68fR6hKFBWoOqmxqUHwJsks5qSQdagaJpZM4JDtYq>.
> >
> 
> 
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/554#issuecomment-230352171

-- 
Juan Cruz Viotti
Software Engineer, Resin.io

**Comment by jviotti** [comment] 2016-07-07 19:32
Hi @act78723 ,

I've been trying to reproduce this one for a while without luck. I did encounter the following discussions about a very similar issue that happens exactly on the Mate desktop:

- https://github.com/mate-desktop/mate-panel/issues/57
- https://bugs.launchpad.net/ubuntu-mate/+bug/1415048
- http://askubuntu.com/questions/419641/panel-apps-try-to-launch-in-xterm-even-though-it-isnt-installed

The weird thing is that the bug mentioned in those discussions happens when you create a custom application launcher with "Application in terminal" type, which I highly doubt AppImages are doing.

Are you creating a custom launcher for Etcher, or are you running it with the image that was installed by the dialog presented when you opened Etcher for the first time?

**Comment by jviotti** [comment] 2016-07-07 19:35
Also, do you mind pasting the contents of your application launcher? It should be in `$HOME/.local/share/applications` or `/usr/local/share/applications` apparently.

**Comment by jviotti** [comment] 2016-07-07 19:38
Its indeed lacking `Terminal=true` in my system (Ubuntu 16.04 x64 w/Unity):

```
[Desktop Entry]
Name=Etcher
Exec=/home/parallels/Projects/etcher/etcher-release/installers/Etcher-linux-x64.AppImage
Comment=Burn images to SD cards & USB drives, safe & easy
Icon=/home/parallels/.cache/thumbnails/normal/62aff500cfa829ae140de5e723814ce2.png
Type=Application
X-Desktop-File-Install-Version=0.22
X-AppImage-Comment=Generated by ./bin//elevate.wrapper
TryExec=/home/parallels/Projects/etcher/etcher-release/installers/Etcher-linux-x64.AppImage
```

**Comment by jviotti** [comment] 2016-07-07 19:38
I'm downloading your exact Linux Mint version, we'll see in a minute...

**Comment by act78723** [comment] 2016-07-08 00:52
That is exactly how I'm running it. Custom launcher/app in terminal.

**Comment by jviotti** [comment] 2016-07-08 14:13
Hi @act78723 ,

Thanks for confirming that. There are plenty of workarounds described in the websites I pasted above, although the real fix would be to not use `Terminal=true` in your launcher, since its not necessary.

I'm closing this as Linux Mint known issue.

**Closed by jviotti** 2016-07-08 14:13 UTC
Labels: platform:linux, ready, type:bug

**Comment by act78723** [comment] 2016-07-08 14:17
Thank you for checking this out
