### ISSUE TITLE
Windows: Unmount Failed

### ISSUE THREAD

**Issue by lee-lvd** [resin-io/etcher#1370] opened 2017-04-29 21:25 UTC
- **Etcher version:**
- **Operating system and architecture:**
- **Do you see any meaningful error information on DevTools?**

font grey on grey is very hard to read.

I am on Windows 7

1.0.0-rc.4

I am trying to write 3 different SD cards

I tried putting on 
"WeatherStation.img"

I tried putting on
"2017-04-10-raspbian-jessie-lite.img"

I tried putting on 
"2017-04-10-raspbian-jessie.img"

all three failed 
here is the results from the last one I tried
And I am not sure why I can not copy the text to paste here,
I did a window copy using paint to get a copy of the error Unmount failed 
at Error (native)

![image](https://cloud.githubusercontent.com/assets/3086592/25559006/c8f4a222-2cef-11e7-9087-f2130b3aef17.png)

**Comment by jviotti** [comment] 2017-05-01 13:57
Hey there,

Thanks for reporting. Can you open DevTools by using Ctrl+Alt+I, going to the Console pane, and pasting everything you see there?

The logging information there will help us see what is really going on.

**Comment by lurch** [comment] 2018-02-26 16:03
Perhaps this should be closed as "can't reproduce", unless @lee-lvd is able to provide more info?

Regarding "font grey on grey is very hard to read." see #1721

**Comment by jhermsmeier** [comment] 2018-02-26 16:55
The unmounts failing on Windows is still a very prevalent issue, which will require some intricate work and testing in [mountutils](https://github.com/resin-io-modules/mountutils) – so I think it'd be good to keep this open, also for people to add info to it

**Comment by jhermsmeier** [comment] 2018-03-09 19:23
Ref duplicates https://github.com/resin-io/etcher/issues/2092 and https://github.com/resin-io/etcher/issues/2110

**Closed** 2018-10-15 12:51 UTC
Labels: component:unmount, platform:windows, type:bug
