### ISSUE TITLE
Etcher CLI Win x86 (32-bit) v1.3.1

### ISSUE THREAD

**Issue by mauricionh** [resin-io/etcher#1990] opened 2018-01-24 02:39 UTC
- **Etcher version:** Etcher CLI Win x86 (32-bit) v1.3.1
- **Operating system and architecture:** Windows 7 Ultimate
- **Image flashed:** N/A
- **Do you see any meaningful error information in the DevTools?** The selected drive was not found
We can't find \\.\PHYSICALDRIVE1 in your system. Did you unplug the drive?

Hello, I was previously using version 1.1.2 and had no trouble using \\.\PHYSICALDRIVE addresses to flash images. I was working on a Windows 10  (64-bit) machine and now I need to replicate my setup on a Windows 7 (32-bit) computer, but version 1.3.1 doesn't work (in either) when I use \\.\PHYSICALDRIVE type addresses.

Thank you!

**Comment by jhermsmeier** [comment] 2018-01-31 17:04
The physical drive path needs two backslashes, i.e. `etcher -d \\.\PhysicalDrive5 disk.img` - can you post the command you've been trying to run?

**Comment by mauricionh** [comment] 2018-01-31 18:49
Hello, 

Yes, sorry the physical drive path has 2 backslashes. I was able to execute this command `etcher.exe -d \\.\PHYSICALDRIVE1 -y disk.img` just fine on version 1.1.2. I'm now using both the 64-bit and 32-bit executables of version 1.1.2 and they work great.

**Comment by jhermsmeier** [comment] 2018-01-31 18:56
Right, and that doesn't work with the Etcher v1.3.1 CLI?

**Comment by mauricionh** [comment] 2018-01-31 19:02
That's correct. I'm pretty sure about it, but I'll triple check later today. I'm using a basic python script (which is working perfectly with version 1.1.2 64-bit and now with the 32-bit version. I run with admin privileges, and the command is always the same (I always double check the drive path). I'll share my findings!

**Comment by mauricionh** [comment] 2018-01-31 19:27
![image](https://user-images.githubusercontent.com/29389709/35642966-aba45370-0679-11e8-8931-4a726ef0b0ad.png)

**Comment by mauricionh** [comment] 2018-01-31 19:33
I just tested with version 1.2.1 (64-bit) and it works.. 
![image](https://user-images.githubusercontent.com/29389709/35643246-95948d74-067a-11e8-8e2d-59ff3494663c.png)

**Comment by jhermsmeier** [comment] 2018-01-31 19:36
Thanks @mauricionh – that's odd, will have a look!

**Comment by mauricionh** [comment] 2018-01-31 19:46
Sure, no problem!

**Comment by jhermsmeier** [comment] 2018-01-31 22:17
![etcher-v1 3 1-cli](https://user-images.githubusercontent.com/244907/35650506-9d20b5ce-06dc-11e8-832d-ffddb1c03ef0.png)

![etcher-v1 3 1-cli-y](https://user-images.githubusercontent.com/244907/35650505-9cea1cbc-06dc-11e8-90b5-cafb553ee378.png)

Well that's interesting; I couldn't reproduce this behavior (on Windows 10) - does it only fail for you on Windows 7, or does 10 also not work?

**Comment by mauricionh** [comment] 2018-02-01 00:17
Mmm.. The last screen snips I shared were taken from a Windows10 64-bit Pro.

**Comment by lurch** [comment] 2018-02-28 16:21
@jhermsmeier I assume the fact that you were using mixed-case (i.e. `\\.\PhysicalDrive2`) and @mauricionh is using upper-case (i.e. `\\.\PHYSICALDRIVE1`) has no bearing on this problem?

**Comment by jhermsmeier** [comment] 2018-02-28 17:12
It shouldn't – Windows is generally case-insensitive

**Comment by jhermsmeier** [comment] 2018-03-01 17:55
Turns out the casing is actually part of the problem here, because the part that lists the drives uses a different version of `drivelist` (fixed in https://github.com/resin-io-modules/resin-cli-visuals/pull/49). Further there are some dependencies that needed updating (#2095) for the packaged CLI to resolve native bindings properly, and a bug in the writer's error handling (#2097) also contributes to the CLI being mildly broken atm.

**Comment by cabbagecreek** [comment] 2018-03-02 07:21
![image](https://user-images.githubusercontent.com/713313/36887640-6c5a9590-1df2-11e8-8e6a-7b437876b8f8.png)
This is a workaround/quickfix
The physicaldriveX MUST be with Capital P and Capital D like in \.\PhysicalDrive1 (not \.\PHYSICALDRIVE1 like "wmic diskdrive list" is reporting..

**Comment by jhermsmeier** [comment] 2018-03-21 21:47
Closing, as all relevant PRs (https://github.com/resin-io/etcher/pull/2095, https://github.com/resin-io/etcher/pull/2097, https://github.com/resin-io/etcher/pull/2099) have been merged

**Closed by jhermsmeier** 2018-03-21 21:47 UTC
Labels: component:cli, platform:windows, type:bug
