### ISSUE TITLE
PGP key reference in doc for getting .deb version fails

### ISSUE THREAD

**Issue by mhmoran** [resin-io/etcher#2132] opened 2018-03-22 19:23 UTC
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
Executing: /tmp/tmp.1LSj3Bdf6q/gpg.1.sh --keyserver
hkp://pgp.mit.edu:80
--recv-keys
379CE192D401AB61
gpg: requesting key D401AB61 from hkp server pgp.mit.edu
gpgkeys: key 379CE192D401AB61 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm

**Comment by jhermsmeier** [comment] 2018-03-22 19:26
Duplicate of https://github.com/resin-io/etcher/issues/1786

**Comment by jhermsmeier** [comment] 2018-03-22 19:27
This is an transient error – the MIT key server has been a bit unstable lately; retrying a couple times should resolve it.

**Comment by jhermsmeier** [comment] 2018-04-06 18:52
Closing as duplicate

**Closed by jhermsmeier** 2018-04-06 18:52 UTC
Labels: resolution:duplicate, type:support
