### ISSUE TITLE
Etcher CLI usage examples

### ISSUE THREAD

**Issue by tzikis** [resin-io/etcher#1732] opened 2017-09-17 22:49 UTC
- **Etcher version: 1.1.2
- **Operating system and architecture: macOS
- **Image flashed: Custom Raspbian for Resin.io

Hey guys, I tried using the Etcher CLI to burn the image for the Beast, and since there were no CLI usage examples on the [page](https://etcher.io/cli/), I used the one that  `etcher -h` suggests.

In the suggestions, the first parameter to etcher is the etcher.js file (more specifically, it's `/snapshot/etcher/dist/Etcher-cli-1.1.2-darwin-x64-app/lib/cli/etcher.js`) but apparently that should just be ignored, so perhaps this should be fixed.

**Comment by lurch** [comment] 2017-09-19 13:13
Duplicate of #1452  ;-)

**Closed by lurch** 2017-09-19 13:13 UTC
Labels: component:cli, platform:all, type:bug
