### ISSUE TITLE
Stuck at 40% during flashing

### ISSUE THREAD

**Issue by RebelReign** [resin-io/etcher#1865] opened 2017-11-18 18:01 UTC
Trying to write this .img file to an SD card and I'm stuck at 40% in flashing as far as i can tell there are no errors that would be causing this.
- Etcher version: v1.1.2 - 2017-08-07
- Operating system and architecture: kali linux, x86_64
- Image flashed: 2016-05-10-raspbian-jessie-lite-video-looper.img

- Do you see any meaningful error information in the DevTools?
[-1511027911872.log](https://github.com/resin-io/etcher/files/1484864/-1511027911872.log)

ignore the dbg nonsense at the bottom that was me

**Comment by jhermsmeier** [comment] 2017-11-18 19:22
Duplicate of #1423

**Comment by jhermsmeier** [comment] 2017-11-18 19:24
Thanks for reporting! This has been fixed in https://github.com/resin-io/etcher/pull/1843 and will be included in the next release.

**Closed by jhermsmeier** 2017-11-18 19:24 UTC

**Comment by RebelReign** [comment] 2017-11-18 19:38
Thank you for the response!
