### ISSUE TITLE
Windows 10 USB devices will not eject if task manager is open.

### ISSUE THREAD

**Issue by fourthhorsem4n** [resin-io/etcher#1316] opened 2017-04-17 19:39 UTC
- Etcher version: any version
- Operating system and architecture: windows 10 32 and 64 bit versions
- Do you see any meaningful error information on DevTools? N/A

Just something I have noticed with windows 10. The OS will not eject USB devices if the task manager is open giving the message that the device is busy. Closing the task manager then ejecting the USB device solves this problem.

**Comment by jviotti** [comment] 2017-04-18 15:21
Thanks a lot for the valuable observation. I'll try to reproduce this later today.

**Comment by lurch** [comment] 2017-04-20 11:42
How bizarre! I don't have Windows 10 myself, but were you able to reproduce @jviotti ?

**Comment by jviotti** [comment] 2017-04-20 18:24
I tested this out, both from master, and from v1.0.0-rc.3 and I can't seem to be able to reproduce; the drive gets ejected just fine.

Do you mind pasting a screenshot of the error window?

**Comment by lurch** [comment] 2018-02-26 15:35
Unless @fourthhorsem4n is able to provide more info, this should probably be closed as "can't reproduce" ?

**Comment by jhermsmeier** [comment] 2018-02-26 18:08
I've come across this once or twice I think, and thought it was due to the TaskManager being open, but couldn't reliably reproduce it – I think this might very well be classified as a Windows bug, and marked wontfix, if we still can't reproduce it.

**Comment by jhermsmeier** [comment] 2018-04-06 20:35
Duplicate of https://github.com/resin-io/etcher/issues/1370

**Closed by jhermsmeier** 2018-04-06 20:35 UTC
Labels: component:unmount, platform:windows, type:bug
