### ISSUE TITLE
removable drive not detected

### ISSUE THREAD

**Issue by mtantaya** [resin-io/etcher#1440] opened 2017-05-16 15:39 UTC
- Etcher-1.0.0-win32-x86
- windows 7 32bit ultimate sp1
- raspbian jessie
- *yes, at the first starting. here is the error i capture it
![resin](https://cloud.githubusercontent.com/assets/28735024/26114669/1845c6da-3a88-11e7-8a65-f89dd0f1c9fb.JPG)

...........................................................................................................................................................................................
and... my removable device is not detected even i enabled "unsafe mode"
![error](https://cloud.githubusercontent.com/assets/28735024/26114715/3ac4c2e2-3a88-11e7-92db-227ac5d544cd.JPG)

thanks for your support and help

**Comment by lurch** [comment] 2017-05-16 15:46
Looks like a duplicate of #1054 ?

**Comment by jviotti** [comment] 2017-05-16 16:27
Indeed. The issue is that if the drive detection script fails, then it won't attempt to scan again (so we don't get hundreds of similar issues).

@mtantaya We're in the process of re-implementing the drive scanning routines in C++, which should hopefully fix this issue.

BTW, are you running any anti-virus software? If so, which?

**Closed by jviotti** 2017-05-16 16:27 UTC
