### ISSUE TITLE
Install ISO in one Partition of usb Disk

### ISSUE THREAD

**Issue by sae13** [resin-io/etcher#453] opened 2016-06-07 07:16 UTC
so i have two partition on my usb disk
first is sdc1 which i want it be empty and ntfs! cuz windows only can read first partition of usb disk

second is sdc2 which i wanna install my iso on that.

**Comment by jviotti** [comment] 2016-06-07 18:43
Hi @sae13 ,

The ISO already contains information about the partitions that should be created in your drive (a MBR for example). The partitions that are created in your drive are not up to Etcher, but up to your image, therefore we have to write the image to the beginning of your drive (otherwise it'll not boot).

**Comment by sae13** [comment] 2016-06-08 12:00
with gparted i make my usb disk two part. then I format part 2 as fat32 and make thats flag as bootable.
after that i install manjaro on thats partition on usb disk and it works with no problem

**Comment by jviotti** [comment] 2016-06-09 19:16
I see. I never did that before. I'll re-open for investigation, although I don't know how this would play with images that contain a non-trivial partition table. What software are you using to flash an image to a partition?

**Comment by Donneur2lumiere** [comment] 2016-12-18 21:05
lili usb creator do it without any problems. Perhaps only put iso in first partition sometimes. But it works

**Comment by mymike00** [comment] 2017-06-17 16:28
Yeah, LinuxLive USB Creator (Lili), unetbootin and another program doesn't touch the partition already present in the usb/hard disk. So it's possible to do, but instead of them I prefer Etcher because of the graphic, LiLi doesn't work on linux etc... I'll love you if you add a feature like that

**Comment by mymike00** [comment] 2018-02-23 16:34
@lurch yeah, they seems very similar

**Comment by jhermsmeier** [comment] 2018-02-23 17:42
Yeah, good catch @lurch!
Duplicate of #414

**Comment by jhermsmeier** [comment] 2018-02-23 17:42
Duplicate of #414

**Closed by jhermsmeier** 2018-02-23 17:42 UTC
Labels: component:writer, platform:all, type:feature
