### ISSUE TITLE
[Suggestion] Add support for more archive formats

### ISSUE THREAD

**Issue by Modelmat** [resin-io/etcher#1672] opened 2017-08-04 22:16 UTC
- **1.1.1**
- **Windows**

With 7zip ([here](http://www.7-zip.org/download.html)), you can decompress basically every archive type. Etcher, for example, does not support .7z files. You could either package the command line executable or modify the source code to include this support in Etcher (it is open-source, after all)

Thanks.

**Comment by lurch** [comment] 2017-08-05 09:39
Duplicate of #711

**Closed by lurch** 2017-08-05 09:39 UTC
Labels: resolution:duplicate
