### ISSUE TITLE
Error "You're not authorized to perform this operation"

### ISSUE THREAD

**Issue by evanoloughlin** [resin-io/etcher#1960] opened 2018-01-08 15:14 UTC
I get the following error when trying to write an image to my SD card:
> You're not authorized to perform this operation
> Please ensure you have necessary permissions for this task
This occurs after ~ 86% has been completede
Etcher is grand SU permissions when the flash begins

- Etcher version: 1.3.0
- Operating system and architecture: Ubuntu 16.04.3 (Linux 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
- SD card image created using DD

**Comment by lkmcdo** [comment] 2018-01-09 06:05
Same feedback but using the appimage on OpenSUSE 42.3 (up to date patches on x86_64, idk where to find a full string).

Granted sudo when prompted but did not run etcher using SU.

**Comment by manuti** [comment] 2018-01-25 23:23
I think this can be related to a broken SD after using Etcher 1.3.0 version @
Duplicate of #1955

**Comment by lurch** [comment] 2018-01-26 10:59
@manuti Nope, this isn't a duplicate of that issue ;-)  Even when an SD card is 'broken', Etcher works at such a low level that it's still able to write a new image to that SD card.

@evanoloughlin It seems weird for Etcher to suddenly have a permissions problem 86% of the way through writing.
What SD card are you using (make, model, size, etc.) ? What SD card-reader are you using? How big is the image that you're trying to write to your SD card?

Oh, and I've just noticed that you said "Etcher version: 1.3.0" - that's a known buggy version, please upgrade to Etcher v1.3.1 and see if you still have problems.

**Comment by manuti** [comment] 2018-01-26 11:44
@lurch OK, maybe is not duplicated but I think is related to the other issue, you can see my post in armbian forum https://forum.armbian.com/topic/2419-armbian-for-amlogic-s905-and-s905x/?do=findComment&comment=47039 
I have the same ~80% error in a 16GB Samsung Evo used with Recalbox without problems and a completely new 16GB Lexar 300x. I try  with 3 different SD adaptor, 2 different USB to microSD reader ... always thinking that's a problem with the images.

**Comment by gehaslam** [comment] 2018-02-20 20:56
I had the same problem using both Win32 disk imager and and etcher (WINDOWS 7  OS). Wes successful with etcher after System reboot. It's rare that I've experienced these kinds of problems using Linux.

**Comment by lurch** [comment] 2018-02-22 16:03
Thanks @gehaslam  Good to hear that the "try turning it off and on again" still fixes Windows problems :rofl:

**Comment by lurch** [comment] 2018-02-28 16:13
@evanoloughlin Do you still have problems with Etcher 1.3.1 ?

**Comment by evanoloughlin** [comment] 2018-03-01 11:00
@lurch - I have not reproduced the issue so far with the latest version of Etcher (1.3.1)

**Comment by jhermsmeier** [comment] 2018-03-01 11:26
@evanoloughlin that's good news :)
Closing this then, as we've also not seen this come up in quite a while

**Closed by jhermsmeier** 2018-03-01 11:26 UTC
Labels: component:writer, platform:linux, type:bug

**Comment by raydot** [comment] 2018-03-26 22:11
<raises hand> I've got the issue.  Tried from both Etcher and Etcher CLI on OSX Sierra 10.12.3.  Here's the output from the CLI:

~/Documents/RaspPi --> sudo etcher ./2018-03-13-raspbian-stretch.zip
? Select drive /dev/disk1 (15.9 GB) - SD Card Reader
? This will erase the selected drive. Are you sure? Yes
You don't have access to this resource

Please ensure you have necessary permissions to access this resource

And then from the DTP app:

cations/Etcher.app/Contents/Resources/app.asar/node_modules/raven-js/dist/raven.js:55 {"stack":"Error: EACCES: permission denied, open '/dev/rdisk1'","message":"EACCES: permission denied, open '/dev/rdisk1'","code":"EACCES"}

(There's more, but that seemed most relevant.)  

Disk is SanDisk Ultra Plus 16GB.

Anything else I can add?

**Comment by JulianNorton** [comment] 2018-04-16 02:05
On windows 10: 
Upon beginning the flash I get the windows error:
```
You're not authorized to perform this operation
```
Then immediately the Etcher error:
```
Oops, seems something went wrong.
```

1. Error for both 1.2.1 and 1.3.1.
2. I also tried "running as an administrator" as 1.3.1 and same error.
3. Rebooted, same error in 1.3.1
3. Enabling `unsafe mode` resulted in the same error.

**Comment by JulianNorton** [comment] 2018-04-17 15:32
Want to recommend reopening this issue and tag it as Windows specific. I flashed on Mac with no problem.

**Comment by JulianNorton** [comment] 2018-04-17 16:36
@jhermsmeier I recommend reopening this issue, or creating a new issue, to clarify the error message. I believe the root cause of this is the SD card not staying unmounted.

**Comment by raydot** [comment] 2018-04-18 21:41
I flashed on Windows with no problem but couldn't get it working on Mac...could it be make/model of computer?
________________________________

**Comment by rahul260792** [comment] 2018-04-26 17:25
I had the same issue on Windows 10 I fixed the issue by disabling Windows Defender as it was not allowing Etcher to flash the image in micro sd card.

**Comment by fwcd** [comment] 2018-05-09 19:32
@rahul260792 That solved it, thank you!

**Comment by lfg6000** [comment] 2018-06-02 13:51
I had this issue when trying to flash raspbian to a 32gb sandisk sd card on Win10
  You're not authorized to perform this operation
  Please ensure you have necessary permissions for this task

Fixed by temporarily turning off Win 10 Controlled File Access
- open windows defender
- open virus & threat protection
- open ransomware protection
- turn off controlled file access
- Etcher was able to flash the raspbian image to the sd card
- turn controlled file access back on

**Comment by marcoamm** [comment] 2018-07-19 16:55
@lfg6000 Worked for me, and the solution makes sense. Thanks!

**Comment by CapitanLab** [comment] 2018-08-04 01:36
I turn off all antivirus etc. and it works well.

**Comment by DubTech247** [comment] 2018-09-11 18:14
> I encountered the same problem in Win 7, and it turned out to be caused by Acronis True Image's 'active protection' function. Turn off the function and I can run the flash now.

@nestser 
i love you and wish to have your babies

**Comment by drgruney** [comment] 2018-09-23 15:55
I gave Windows defender an application exception for Etcher in Controlled Folder settings :D

**Comment by consolacion** [comment] 2018-10-19 12:40
none of this helped, so I was forced to go back to Win32 Disk Imager

**Comment by klccjeremy** [comment] 2018-10-24 12:44
works well before i updated to V1.4.5, after update had the same error msg

**Comment by jjahn504** [comment] 2019-02-01 14:35
I encountered the same problem in Win 10, Etcher1.4.9, and I turned off the **'Windows Defender**->real time service' and I can run the flash now.

**Comment by UmerFarooqBiomedical** [comment] 2019-02-20 20:44
> I had this issue when trying to flash raspbian to a 32gb sandisk sd card on Win10
> You're not authorized to perform this operation
> Please ensure you have necessary permissions for this task
> 
> Fixed by temporarily turning off Win 10 Controlled File Access
> 
> * open windows defender
> * open virus & threat protection
> * open ransomware protection
> * turn off controlled file access
> * Etcher was able to flash the raspbian image to the sd card
> * turn controlled file access back on

Thank you so much, Man. I spent my whole day under stress and tried 2 different cards and faced the same problem, again and again, a hundred time till I find your comment. This solved my problem. A lot-lot-lot of thank. Love from Pakistan.

**Comment by DubTech247** [comment] 2019-02-20 21:09
Turns out it was some sort of drive protection feature from a recently
installed Acronis program, switched it off and it worked fine

**Comment by lurch** [comment] 2019-02-21 13:05
@thundron Sounds like it might be useful to include these various workarounds into the docs or FAQ?

**Comment by haleypearse** [comment] 2020-03-14 23:44
I solved this on a mac by opening with sudo from the terminal by typing 
sudo /Applications/Etcher.app/Contents/MacOS/Etcher

**Comment by bestK** [comment] 2020-03-22 12:00
update to last version to fixed in MacOS catalina

**Comment by saharshtapi** [comment] 2020-03-25 16:16
I had the same issue. Go to windows security > virus and threat > under ransomware click on manage ransomware protection and turn off control folder access. that's it
