### ISSUE TITLE
Problems with dots in MacOSX 10.10.5

### ISSUE THREAD

**Issue by rafaeltovar** [resin-io/etcher#496] opened 2016-06-20 18:01 UTC
Hi, Etcher don't open image files when have dots in the name. For example 'elementary-3.0.8.iso'. In MacOSX 10.10.5.

**Comment by jviotti** [comment] 2016-06-20 18:02
Hi @rafaeltovar ,

This is a duplicate of  https://github.com/resin-io/etcher/issues/492, which has just been closed. I'm uploading a new version with a fix as I write, stay tuned!

**Closed by jviotti** 2016-06-20 18:02 UTC

**Comment by rafaeltovar** [comment] 2016-06-20 18:08
Oh! Sorry! :(

**Comment by jviotti** [comment] 2016-06-21 01:44
No need to feel sorry! Thanks for reporting this, and forgive us for introducing this regression that annoyed so many Elementary OS users.

You went all the way to discover the workaround I shared in the other issue by yourself, which is super awesome!

**Comment by jviotti** [comment] 2016-06-21 01:47
I've published v1.0.0-beta.9 with the fix, which you can get from the website!
