### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jeremy-daily** [resin-io/etcher#706] opened 2016-09-17 22:37 UTC
Not sure if this feedback helps. Running Windows 7-64 and using a Samsung Ultra SD card.
![image](https://cloud.githubusercontent.com/assets/7162728/18611397/5c1c990e-7cfd-11e6-8f49-35f8b4cb5af5.png)
![image](https://cloud.githubusercontent.com/assets/7162728/18611399/62a69efa-7cfd-11e6-9b30-f03624fb7dc3.png)

**Comment by jviotti** [comment] 2016-09-20 01:09
Hi @jeremy-daily ,

This issue reports the same problem as https://github.com/resin-io/etcher/issues/642, so I'll close this one and continue discussion in the other one.

As explained in more detail in the linked issue, the issue is that the Etcher CLI is spawned by the GUI, which then emits progress to stdout as JSON encoded lines. For some reason, looks like a line is not completely flushed to stdout before we attempt to decode it, causing JSON errors.

I'm still investigating a way to do a proper fix, but for now, I believe that this is issue is very sporadic, and simply retrying should work fine.

**Closed by jviotti** 2016-09-20 01:09 UTC
