### ISSUE TITLE
Unable to select a 64GB SD Card 

### ISSUE THREAD

**Issue by Dudematters** [resin-io/etcher#2390] opened 2018-06-13 13:38 UTC
- **Etcher version: 1.4.3** 
- **Operating system and architecture: MacOS 10.13.5** 
- **Image flashed: volumio-2.389-2018-03-26-pi.img.zip** 

I am trying to flash an 64GB SD Card for a raspberry pi with volumio. Ether sees the SD card but won't let me select it. It selects it for a brief moment but deselects it directly. I can format it on my Mac but nothing helps to make Etcher accept my card.

![screen 2018-06-13 at 15 34 28](https://user-images.githubusercontent.com/40238967/41354591-acb28ea8-6f1f-11e8-8334-72bbca363995.png)

**Comment by jhermsmeier** [comment] 2018-06-13 14:11
Hey there, that's a bug we fixed in version 1.4.4; I'd recommend to update & try again

**Comment by jhermsmeier** [comment] 2018-06-13 14:12
Duplicate of https://github.com/resin-io/etcher/issues/2267

**Comment by jhermsmeier** [comment] 2018-06-13 18:37
Closing as duplicate

**Closed by jhermsmeier** 2018-06-13 18:37 UTC
Labels: resolution:duplicate
