### ISSUE TITLE
Upgrade to npm v5

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1528] opened 2017-06-17 01:14 UTC

**Comment by lurch** [comment] 2017-06-20 23:06
Duplicate of #1487 ?

**Comment by jviotti** [comment] 2017-06-21 15:35
Well, that's a PR while this is an issue, so I guess its fine.

**Comment by mykter** [comment] 2018-02-10 17:36
Heads up: I was using your shrinkwrap cleaner for platform specific dependencies (thanks!) and after upgrading to npm 5 no longer need it. After removing and regenerating the shrinkwrap, npm now just warns about missing optional dependencies that are in the shrinkwrap (finally!).

**Closed** 2018-10-15 12:57 UTC
Labels: component:build system, platform:all, type:feature
