### ISSUE TITLE
Window fails to load and remains blank after upgrading Etcher

### ISSUE THREAD

**Issue by WasabiFan** [resin-io/etcher#1031] opened 2017-01-17 04:23 UTC
- **Etcher version:** Beta 18 (upgraded from 17)
- **Operating system and architecture:** Windows 10 x64
- **Do you see any meaningful error information on DevTools?** See below.

After clicking the final button in the Etcher installer with the "run Etcher" box checked, the application opened without any content other than some upper-right buttons and the bottom text.

![image](https://cloud.githubusercontent.com/assets/3310349/22007584/a966f440-dc28-11e6-9075-387338de20f7.png)

I had closed the previous version of Etcher before starting the installer for the new one. The dev tools look like this:

![image](https://cloud.githubusercontent.com/assets/3310349/22007606/d8cddf5a-dc28-11e6-87cb-8fe2ee06d152.png)

The error text is:

```
Uncaught Error: Cannot find module 'etcher-image-stream'
C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:4631 Uncaught Error: [$injector:modulerr] Failed to instantiate module Etcher due to:
Error: [$injector:nomod] Module 'Etcher' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=Etcher
    at C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:68:12
    at C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:2075:17
    at ensure (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:1999:38)
    at module (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:2073:14)
    at C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:4608:22
    at forEach (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:321:20)
    at loadModules (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:4592:5)
    at createInjector (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:4514:19)
    at doBootstrap (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:1751:20)
    at bootstrap (C:\Program Files (x86)\Etcher\resources\app.asar\node_modules\angular\angular.js:1772:12)
http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=Etcher&p1=Error%3A%…r%5Cresources%5Capp.asar%5Cnode_modules%5Cangular%5Cangular.js%3A1772%3A12)
```

The window still fails to load if I close the app and open it again. It's worth noting that I had opened the Etcher installation directory in File Explorer (for #1030) during the installation, but did not open any files or otherwise prompt it to try loading them. There were no errors that the installer reported.

**Comment by WasabiFan** [comment] 2017-01-17 04:31
I can confirm that this isn't localized to one PC; upgrading on another one exhibits the same behavior. Although it looks like you've probably already figured it out.

**Comment by jviotti** [comment] 2017-01-17 04:36
This is really weird. I can reproduce the problem on Windows indeed, but not on OS X nor Windows. I took off the Windows builds from S3 for now. I'm investigating if why this dependency has not been included in the package.

**Comment by WasabiFan** [comment] 2017-01-17 04:41
Are the zip builds functional? (I can't test because they've been removed from S3 😆)

**Comment by jviotti** [comment] 2017-01-17 04:44
Hi @WasabiFan ,

Looks not. I took off the bad builds from S3 so users get pointed to v1.0.0-beta.17 while we fix the issue. 

I'm tracking it down... Seems like an npm issue on my Windows build machine. I'll keep you updated on this ticket!

**Comment by jviotti** [comment] 2017-01-17 05:17
So the issue seems to be that npm insists on installing a platform specific development dependency for some reason, causing a certain package (`etcher-image-stream`) to be removed.

I've downgraded npm without luck, however discovered that the installation works fine if I call npm from MinGW instead of from `cmd.exe`, which makes no sense at all :/

I'll build from MinGW and release so we have everything up and running and will continue to investigate the issue.

**Comment by jviotti** [comment] 2017-01-17 15:59
I'm closing this issue. Seems like an npm Windows glitch. I've released MinGW builds that work fine (at least here), and will be putting extra effort to finally move releases to the CI servers for the next one.

**Closed by jviotti** 2017-01-17 15:59 UTC
Labels: component:build system, platform:windows, type:bug
