### ISSUE TITLE
Etcher losing access to the drive

### ISSUE THREAD

**Issue by brianmituka** [resin-io/etcher#1492] opened 2017-06-06 07:39 UTC
- **Etcher version:** 1.0.0
- **Operating system and architecture:** linux mint cinnamon 32bit
- **Image flashed:** raspbian jessie

 **that is the response I get when I try to flash my Sd card**
![etcher1](https://cloud.githubusercontent.com/assets/21999457/26818222/84f130ba-4aa2-11e7-87f0-03b85b503bce.png)

**that is the output I get from the developer's console**
`/tmp/.mount_41RM6C/usr/bin/resources/app.asar/node_modules/raven-js/dist/raven.js:51 Tue Jun 06 2017 10:05:58 GMT+0300 (EAT) Drive unplugged ({"image":"/home/mots/Desktop/raspbian/2017-04-10-raspbian-jessie.img","drive":{"device":"/dev/mmcblk0","description":"SL08G","size":7948206080,"mountpoints":[],"raw":"/dev/mmcblk0","protected":false,"system":false,"name":"/dev/mmcblk0"},"uuid":"b01b2a79-6b10-44bb-bdba-65c474fe7c4e","unmountOnSuccess":true,"validateWriteOnSuccess":true})`

**After the failed flashing, this is what I get when I try to open the sd card**
`Error mounting /dev/mmcblk0p1 at /media/mots/4D72-10FE: Command-line `mount -t "vfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,shortname=mixed,utf8=1,showexec,flush" "/dev/mmcblk0p1" "/media/mots/4D72-10FE"' exited with non-zero exit status 32: mount: wrong fs type, bad option, bad superblock on /dev/mmcblk0p1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
`

**Comment by lurch** [comment] 2017-06-06 11:22
Are you sure your SD reader isn't faulty / flaky, as the error message suggests?
Could you provide more details about which SD reader you're using?

Hmmm, I guess `/dev/mmcblk0` might indicate that it's an internal SD reader slot on a laptop? If so could you provide us with details about your laptop?
Have you ever had any other problems with your SD slot being unreliable with other programs? Do you also have a USB SD adaptor that you're able to test with?

**Comment by jviotti** [comment] 2017-06-06 14:12
Yeah, this really looks like a faulty card, or reader. Its known that these types of issues can trigger a "drive unplugged" event, and `mount` seems to confirm that (`mount: wrong fs type, bad option, bad superblock on /dev/mmcblk0p1`).

I'll close this, since there's probably nothing we can do from our side.

**Comment by lurch** [comment] 2017-06-06 17:14
The `mount` error just indicates that the image wasn't fully written to the SD card - if you look at @brianmituka 's screenshot closely you can see that Etcher hadn't even got to 1% before the card was 'unplugged', so it's not surprising that nothing could be mounted ;)

@jviotti If you don't mind I'll re-open this for now - as I mentioned in my previous comment `/dev/mmcblk0` indicates that it's (probably) an internal SD-slot, and I'd expect those to be higher-quality than cheap USB SD-adaptors, so I'd like to dig into this a bit deeper...

**Comment by timdonovanuk** [comment] 2017-08-20 12:41
I have this problem with Ethcher using an SD Card reader in Windows 7. Card reader has always worked 100% with other tools such as Win32DiskImager and I use it to transfer photos all the time with no issues.

**Comment by lurch** [comment] 2017-08-20 21:56
@timdonovanuk Are you definitely using the latest version (1.1.2) of Etcher? What's the exact error you see? Can you cut'n'paste your DevTools console logs please? (Press `Ctrl` and `Alt` and `i` at the same time). A screenshot of your error-message might be useful too.
Are you using an internal card reader, or an external (USB) card reader? Can you provide more details about both the SD card you're using and the SD card reader you're using?
If you have the time, can you verify that Win32DiskImager is successfully able to write the exact same disk-image to the exact same SD-card using the exact same card-reader, that Etcher is unable to?

I realise that's a lot of questions, but the more info you can provide, the easier it'll be for us to track down the exact problem ;-)

**Comment by lurch** [comment] 2017-08-20 21:57
Also, if @brianmituka could try testing again with the latest version of Etcher, that'd be really helpful :)

**Closed** 2017-12-04 23:31 UTC
Labels: component:writer, platform:linux, type:support

**Comment by r4mbo7** [comment] 2018-12-04 17:30
Fails after 1% with 1.4.8 just dl...
![image](https://user-images.githubusercontent.com/24637826/49460844-9cd2b100-f7f2-11e8-82e5-f309050dd385.png)

**Comment by neodingo** [comment] 2021-08-21 00:57
I see this behavior currently whenever the source image is on a network share on Windows 10.

**Comment by lurch** [comment] 2021-08-21 05:46
> I see this behavior currently whenever the source image is on a network share on Windows 10.

Duplicate of e.g. #3419 ?

**Comment by neodingo** [comment] 2021-08-21 22:20
That's my best guess, thanks for the link - I was hoping someone would send me to the latest on this.  I'll try again tomorrow and see if I can't gather some logs for additional data as I've got a 100% reproducible case.

**Comment by awsome306** [comment] 2023-06-15 20:42
Perhaps this is pure coincidence, but I was able to resolve this issue on my Windows 10 machine by running balenaEtcher as an administrator.

**Comment by 03stevensmi** [comment] 2023-10-18 13:29
> Perhaps this is pure coincidence, but I was able to resolve this issue on my Windows 10 machine by running balenaEtcher as an administrator.

Thank you,
Where as everyone else here is full of sh** and assumes the worst that my pc is damaged...
And has nothing to do with the software...
Despite everyone saying others work etc etc...?
Sending me into panic mode...

This actually helped! 
"Run-as-administrator" sould in all be the first response or advice anytime this exact question gets asked.
Then if it doesn't work,
Go down the line of what was suggested above.
(Assuming others didn't work that is) ;)

Anyone reading this...
Download the portable version,
Disable controled folders in ransomware protection (its in the windows security virus settings)
(just temp ofc... Make sure when your finished to re-enable it in case you forget)
Right click the program and run as administrator,
Don't use url to flash (that never worked for me)
Select image from folder...
See if it worked for you...
If not...
Then continue here for "help"
Cheers awsome306!
