### ISSUE TITLE
[Feature Request] Modifying SD Card contents automatically after etching

### ISSUE THREAD

**Issue by brainforgeUK** [resin-io/etcher#1668] opened 2017-08-04 09:01 UTC
- 1.1.1
- Windows 10
- img containing 2 or more filesystems (e.g. Raspbian)
- N/A

The Etcher CLI, either enhanced or included in a cmd script, is possibly the initial way to go here.
Final solution should be included as extra steps in the standard tool interface.

Taking the Raspbian img as an example with a FAT and a Linux partition I want to do this...
Step 0 - Download .img from internet (username+password required).
Step 1 - Write image to SD card as existing (unzip if necessary).
Step 2 - Add extra content to the FAT filesystem (i.e. /boot for Raspbian).
Ideally the solution would be general purpose and user able to select partition N (1 in this case).

Using the etcher CLI the command would look like this:
etcher --source=http://myserver/downloads/master.img.zip --drive=A --partition=1 --extra=myfile.zip

For completeness I suppose --extra=http://.... should also be available.

In the situation I am investigating I have a Raspbian image with a  customised /root partition which runs a script on startup. This will read myfile.zip from /boot and take owner specific custom action.

I could preload /boot with myfile.zip and provide a custom .img for every download.
Uncompressing the master, mounting, compressing takes time and requires root on server.
Prefer to provide master img for download and then a small separate myfile.zip for the custom stuff.

Thoughts? Anyone done similar?
Assume target is a headless Raspberry PI and a 'I know nothing' end user!

**Comment by lurch** [comment] 2017-08-04 09:42
Duplicate of #718 - this is a feature we've got planned tor "Etcher V2" https://resin.io/blog/the-future-of-etcher/

**Closed by lurch** 2017-08-04 09:42 UTC
Labels: resolution:duplicate
