### ISSUE TITLE
Check if an image has a MBR or GPT, and complain if not

### ISSUE THREAD

**Issue by jviotti** [resin-io/etcher#1189] opened 2017-03-17 18:10 UTC
Images without a MBR nor GPR will probably not boot. This simple check covers most edge cases:

- Hybrid ISOs still have a MBR
- Windows images don't have a MBR

**Comment by jhermsmeier** [comment] 2017-03-17 18:14
We should probably still let the user decide if they want to proceed with flashing, to avoid false positives from getting in the way.

**Comment by lurch** [comment] 2017-03-21 23:20
Is this a duplicate of #553 ? ;-)

**Comment by jviotti** [comment] 2017-03-21 23:49
Good catch. I'll close the other one in flavour of this, which sets a clearer way forward.

**Comment by jhermsmeier** [comment] 2017-10-24 21:48
Closing, as has been done in https://github.com/resin-io/etcher/pull/1248

**Closed by jhermsmeier** 2017-10-24 21:48 UTC
Labels: component:writer, platform:all, type:feature
