### ISSUE TITLE
libgconf-2.so.4 missing on Ubuntu 18.02 Beta

### ISSUE THREAD

**Issue by probonopd** [resin-io/etcher#2191] opened 2018-04-10 15:21 UTC
On `ubuntu-18.04-beta2-desktop-amd64.iso` getting

```
me@host:~$ /isodevice/Applications/etcher-1.3.1-x86_64.AppImage 
3654
/tmp/.mount_OjZb9X/usr/bin/etcher-electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by lurch** [comment] 2018-04-10 18:05
Duplicate of #1305 ?

**Comment by probonopd** [comment] 2018-04-10 18:38
Oops, apparently yes, sorry. Closing here, Discussion should continue in #1305.

**Closed** 2018-04-10 18:38 UTC
Labels: component:build system, platform:linux, type:packaging

**Comment by Bes0n** [comment] 2019-03-24 12:31
Finally made possible to run Atom on my Elementary OS by installing this dependency. Thanks

**Comment by Yogesh9900** [comment] 2019-03-25 07:33
Just do this sudo apt -y install libgconf2-4

**Comment by jhonnyW** [comment] 2019-05-01 14:31
on ubuntu 19.04 
Package 'libgconf2-4' has no installation candidate

**Comment by lurch** [comment] 2019-05-01 14:44
@jhonnyW see https://github.com/balena-io/etcher/issues/1305#issuecomment-295298518 about enabling the 'universe' repository.

**Comment by Quintanar777** [comment] 2019-05-01 17:43
> on ubuntu 19.04
> Package 'libgconf2-4' has no installation candidate

apt-get install libgconf-2-4

**Comment by lurch** [comment] 2019-05-01 23:15
@Quintanar777 Oooh, that's interesting. Looks like in 16.04, 18.04 and 18.10 Ubuntu provide a [libgconf2-4](https://packages.ubuntu.com/cosmic/libgconf2-4) dummy package (which presumably depends on the real [libgconf-2-4](https://packages.ubuntu.com/cosmic/libgconf-2-4) package), but from 19.04 onwards Ubuntu only provides a [libgconf-2-4](https://packages.ubuntu.com/disco/libgconf-2-4) package and **not** a libgconf2-4 package.

**Comment by prashantjeena** [comment] 2019-06-10 02:07
> Error can be worked around by
> 
> ```
> sudo apt -y install libgconf2-4
> ```
> 
> Proper solution is to get rid of the dependency, or bundle it

how to repair the same in windows?

**Comment by gregbenner** [comment] 2019-10-23 16:34
> Error can be worked around by
> 
> ```
> sudo apt -y install libgconf2-4
> ```
> 
> Proper solution is to get rid of the dependency, or bundle it.

forgot a hyphen `sudo apt-get install libgconf-2-4`

**Comment by qm3ster** [comment] 2019-11-02 09:55
Does `libgconf2-4` package just pull in `libgconf-2-4` or does it do anything else? Not sure how to check.

**Comment by lurch** [comment] 2019-11-02 14:14
> Does libgconf2-4 package just pull in libgconf-2-4 or does it do anything else?

On Ubuntu 14.04...
```bash
$ dpkg -L libgconf2-4
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libgconf2-4
/usr/share/doc/libgconf2-4/copyright
/usr/share/doc/libgconf2-4/NEWS.Debian.gz
/usr/share/doc/libgconf2-4/NEWS.gz
/usr/share/doc/libgconf2-4/AUTHORS
/usr/share/doc/libgconf2-4/changelog.Debian.gz
/usr/share/doc/libgconf2-4/README
/usr/share/doc/libgconf2-4/TODO
```
and the output of `apt-cache show libgconf2-4` includes "This package is here to ensure smooth upgrades. It can be removed when you see fit.".

**Comment by shiv0304** [comment] 2020-04-29 05:26
Try this: sudo apt --fix-broken install
this should work in 99% case

**Comment by dods2** [comment] 2020-08-23 23:20
Maybe you can try this
'sudo apt-get --fix-broken install'
'sudo apt-get install libgconf-2-4:i386' or 
'sudo apt-get install libgconf-2-4:arm64'

**Comment by Lezette** [comment] 2020-09-15 17:48
> Maybe you can try this
> 'sudo apt-get --fix-broken install'
> 'sudo apt-get install libgconf-2-4:i386' or
> 'sudo apt-get install libgconf-2-4:arm64'

'sudo apt --fix-broken install' worked for me

**Comment by ikwen** [comment] 2021-11-24 14:47
> 

root@debian:/tmp# dpkg -i discord_instal.deb 
Selecting previously unselected package discord.
(Reading database ... 305101 files and directories currently installed.)
Preparing to unpack discord_instal.deb ...
Unpacking discord (0.0.16) ...
dpkg: dependency problems prevent configuration of discord:
 discord depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 discord depends on libc++1; however:
  Package libc++1 is not installed.

dpkg: error processing package discord (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.69) ...
Errors were encountered while processing:
 discord
root@debian:/tmp# apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  discord
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 188 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 305185 files and directories currently installed.)
Removing discord (0.0.16) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for desktop-file-utils (0.26-1) ...
root@debian:/tmp#

**Comment by katomicity** [comment] 2023-09-11 12:03
Get:3 http://deb.debian.org/debian oldstable/main amd64 libgconf-2-4 amd64 3.2.6-7 [428 kB]
Get:4 http://deb.debian.org/debian oldstable/main amd64 libldap-2.4-2 amd64 2.4.57+dfsg-3+deb11u1 [232 kB]


etc/apt/sources.list    is the problem when you comment out or when the comand below is not included
# deb http://deb.debian.org/debian oldstable main non-free contrib
