### ISSUE TITLE
SystemRescueCD 5.0.3 ISO problem

### ISSUE THREAD

**Issue by plittlefield** [resin-io/etcher#1684] opened 2017-08-09 14:35 UTC
When loading the SystemRescueCD ISO file, Etcher warns that the file is not bootable.

So, I have to use the [Manual Method](http://www.system-rescue-cd.org/Installing-SystemRescueCd-on-a-USB-stick/) for making a bootable USB drive.

Etcher Version: etcher-1.1.2-x86_64.AppImage
Operating System: Ubuntu 16.04.2

**Comment by lurch** [comment] 2017-08-09 17:14
Sounds like this issue is very similar to https://github.com/resin-io/etcher/issues/1644 i.e. the problem isn't  with Etcher, but with the image file being a 'real' ISO.
@jviotti Should we close?

**Comment by plittlefield** [comment] 2017-08-10 07:27
I will try that suggestion and report back.

Paul

**Comment by jviotti** [comment] 2017-08-10 15:08
Awesome. I'll close it, but please re-open if you find something else :)

**Closed by jviotti** 2017-08-10 15:08 UTC
Labels: platform:linux, type:support
