### ISSUE TITLE
Unable to run etcher-cli under windows 10

### ISSUE THREAD

**Issue by tangb** [resin-io/etcher#2279] opened 2018-04-25 21:21 UTC
- **Etcher version:** 
1.4.3
- **Operating system and architecture:** 
Windows 10 pro

It seems etcher-cli bin try to search for files located in c:\snapshot\etcher-cliXXX that doesn't exists.
Is there something I'm doing wrong ?

Thanks for your answer.

This is the output of etcher-cli.exe command:
```
 .\etcher.exe  --unmount false --yes --drive  "\\.\PH
YSICALDRIVE1" "C:\Users\TANGUY~1.BON\AppData\Local\Temp\cleep_cached_Y2xlZXBfMC4wLjEwLnppcA=="
C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

Error: Could not locate the bindings file. Tried:
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\build\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\build\Debug\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\build\Release\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\out\Debug\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\Debug\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\out\Release\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\Release\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\build\default\drivelist.node
 → C:\snapshot\etcher-cli-1.4.3-windows-x64-app\compiled\6.10.3\win32\x64\drivelist.node
    at bindings (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bindings\bindings.js:93:9)
    at Object.exports.list (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\drivelist\lib\drivelist.js:54:7)
    at ImageWriter.getSelectedDevices (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\lib\sdk\writer\index.js:0)
    at ImageWriter.EventEmitter.write.destinationPaths.openSource (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\lib\sdk\writer\index.js:0)
    at EventEmitter.openSource.imageStream.getFromFilePath.asCallback (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\lib\sdk\writer\index.js:0)
    at tryCatcher (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:558:21)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise.module.exports.Promise._resolveCallback (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:630:18)
    at Promise.module.exports.Promise._resolveCallback (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:425:57)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:516:17)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:630:18)
    at PropertiesPromiseArray.module.exports.PromiseArray._resolve (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PropertiesPromiseArray.module.exports.PropertiesPromiseArray._promiseFulfilled (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\props.js:78:14)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:566:26)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.e.Async.drainQueues (C:\snapshot\etcher-cli-1.4.3-windows-x64-app\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by lurch** [comment] 2018-04-25 22:54
Duplicate of #2274 ?

**Comment by tangb** [comment] 2018-04-26 07:12
Yep it seems to be the same issue

**Comment by jhermsmeier** [comment] 2018-04-26 15:34
Duplicate of #2274

**Comment by jhermsmeier** [comment] 2018-04-26 15:35
Thanks @tangb – we'll check it out!

**Closed by jhermsmeier** 2018-04-26 15:35 UTC
Labels: resolution:duplicate
