### ISSUE TITLE
Opening .iso fails where file stored in blank named folder.

### ISSUE THREAD

**Issue by jchurc16** [resin-io/etcher#1593] opened 2017-07-13 14:47 UTC
1.0 - **Etcher version:**
Windows 7 x64 - **Operating system and architecture:**

I have an .iso file stored in a 'hidden' folder on my desktop, blank icon & renamed to ' ' (alt+0160) to keep the desktop clean. When trying to load the file, the below error is produced:

![image](https://user-images.githubusercontent.com/3286699/28172046-42f20df8-67e2-11e7-951c-9bce850a233a.png)

Opening & writing works fine when in any other folder, it looks like it's detecting this as an invalid file path.

**Comment by jhermsmeier** [comment] 2017-07-13 14:50
Looks like this is an instance of https://github.com/resin-io/etcher/issues/1459, and has already been fixed in #1559

**Comment by jhermsmeier** [comment] 2017-07-13 14:53
Also, as a side note; you can right-click on the desktop, then uncheck "Show desktop icons" under "View" in Windows if you want to avoid having to give your files & folders fancy invisible names.

**Comment by jhermsmeier** [comment] 2017-07-13 14:53
Closing as duplicate of #1459

**Closed by jhermsmeier** 2017-07-13 14:53 UTC
Labels: platform:windows, resolution:duplicate, type:bug
