### ISSUE TITLE
Etcher cannot differentiate folder and iso image when folder is named with .iso ending

### ISSUE THREAD

**Issue by lowks** [resin-io/etcher#1926] opened 2017-12-16 01:16 UTC
- **Etcher version: 1.2.1**
- **Operating system and architecture: Mac Mini 2012 running High Sierra**
- **Image flashed: openSuSE leap 42.3**
- **Do you see any meaningful error information in the DevTools? No**

When downloading OpenSuSE 42.3 image it will dump it in a folder called: `openSUSE-Leap-42.3-DVD-x86_64.iso`.  When using Etcher to pick the iso image it wrong assumes that the folder is the iso image and complains that the image is not valid.

**Comment by lurch** [comment] 2017-12-21 17:31
I'm not able to reproduce this on Linux - in fact the browse-file dialog doesn't allow me to select just a folder. I'll test on Windows later.
@jviotti Could you test this on your Mac to see if you can reproduce?

**Comment by jhermsmeier** [comment] 2017-12-21 17:52
This seems to be a bug in the Mac OS file open dialog (?), or more likely configuration thereof.

This is what it looks like in Finder (normal folder expansion):
![screen shot 2017-12-21 at 18 48 32](https://user-images.githubusercontent.com/244907/34268095-ba4231a0-e67f-11e7-8657-9f6af841105e.png)

While the open dialog doesn't allow expansion of the folder, due to the `.iso`:
![screen shot 2017-12-21 at 18 48 08](https://user-images.githubusercontent.com/244907/34268096-ba6398c2-e67f-11e7-88ea-5a1d53b2331c.png)

**Comment by jviotti** [comment] 2017-12-22 17:12
I confirm I can reproduce on macOS. Ping @jhermsmeier. It should be a
quick fix.

On Thu, Dec 21, 2017 at 09:31:26AM -0800, Andrew Scheller wrote:
> I'm not able to reproduce this on Linux - in fact the browse-file dialog doesn't allow me to select just a folder. I'll test on Windows later.
> @jviotti Could you test this on your Mac to see if you can reproduce?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/resin-io/etcher/issues/1926#issuecomment-353410087

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jhermsmeier** [comment] 2018-01-19 14:31
Fixed in #1976

**Closed by jhermsmeier** 2018-01-19 14:31 UTC
Labels: component:formats, platform:osx, platform:windows, type:bug
