### ISSUE TITLE
Broken dependency: libgconf-2

### ISSUE THREAD

**Issue by joelgraff** [resin-io/etcher#2316] opened 2018-05-09 11:23 UTC
Downloaded the latest AppImage and ran it on a clean install of Pop!_OS (Bionic).  Reported a missing dependency.  Installed libgconf-2-4 and it ran without issues.

**Comment by jhermsmeier** [comment] 2018-05-09 11:40
Duplicate of #1305

**Closed by jhermsmeier** 2018-05-09 11:40 UTC

**Comment by probonopd** [comment] 2018-12-31 02:51
Unbelievable it's still not fixed in 1.4.9. It's been almost a year now...

```
me@host:~$ '/home/me/Downloads/balena-etcher-electron-1.4.9-x86_64.AppImage'
2993
/tmp/.mount_G2Gbv3/usr/bin/balena-etcher-electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
