### ISSUE TITLE
Strange error when write 16GB Iso on Windows 7 32bit

### ISSUE THREAD

**Issue by JacekJaworski** [resin-io/etcher#2512] opened 2018-10-18 12:07 UTC
- **Etcher version:** 1.45
- **Operating system and architecture:** Windows 7 32bit
- **Image flashed:** Created by dd on Linux
- **Do you see any meaningful error information in the DevTools?** 
![etchererror](https://user-images.githubusercontent.com/40238842/47152980-802ff780-d2de-11e8-8bd0-b05cc7d5ff09.png)
Bug escription:
I created, trimed, and compress 16GB image from MicroSd card with Raspbian (with Fat32 boot partition and Ext4). I succesfully write this image under Kubuntu 64bit. I failed to do this with Windows 7 32bit. Then I try Rufus and again I successfully wrote the image file.

**Comment by thundron** [comment] 2018-10-18 12:50
Thanks for reporting this, actually a duplicate of https://github.com/resin-io/etcher/issues/2508 which is in the works for next version

**Closed by thundron** 2018-10-18 12:50 UTC
