### ISSUE TITLE
Incorrect "Too Small For Image" error on Windows 10

### ISSUE THREAD

**Issue by rfjakob** [resin-io/etcher#1460] opened 2017-05-19 09:29 UTC
Summary: The SD card is 7948206080 bytes, the image is 7948206080 bytes. On Linux, Etcher reports the correct size and flashes the image without issue. On Windows, Etcher reports 7945620480 bytes, and flashing fails. May be a bug in Windows (see the log on the bottom).

```
Image size      7948206080 bytes
SD card size    7948206080 bytes
Windows reports 7945620480 bytes
```

Edit: Table was the wrong way round (Windows reports a smaller size). Corrected.

- **Etcher version:**

1.0.0

<img width="602" alt="too small" src="https://cloud.githubusercontent.com/assets/286847/26241559/61aed542-3c85-11e7-8ab7-52cf5a953006.PNG">

- **Operating system and architecture:**

Windows 10

- **Image flashed:**

Image that was copied *from an identical SD card*

- **Do you see any meaningful error information in the DevTools?**

### Linux
```
Thu May 18 2017 16:32:06 GMT+0200 (CEST) Select image ({"path":"/tmp/sdcard.rk3399-q7.img","extension":"img","size":{"original":7948206080,"final":{"estimation":false,"value":7948206080}},"logo":false,"bmap":false})

Thu May 18 2017 16:32:51 GMT+0200 (CEST) Toggle drive ({"drive":{"device":"/dev/sdb","description":"Card Reader","size":7948206080,"mountpoints":[],"raw":"/dev/sdb","protected":false,"system":false,"name":"/dev/sdb"},"previouslySelected":false})
```

### Windows 10
```
Fri May 19 2017 11:05:03 GMT+0200 (W. Europe Daylight Time) Select image ({"path":"C:\\Users\\cad\\Downloads\\sdcard.rk3399-q7.img","extension":"img","size":{"original":7948206080,"final":{"estimation":false,"value":7948206080}},"logo":false,"bmap":false})

Fri May 19 2017 11:05:06 GMT+0200 (W. Europe Daylight Time) Toggle drive ({"drive":{"device":"\\\\.\\PHYSICALDRIVE1","description":"Multiple Card  Reader USB Device","size":7945620480,"raw":"\\\\.\\PHYSICALDRIVE1","system":false,"protected":false,"mountpoints":[],"name":"\\\\.\\PHYSICALDRIVE1"},"previouslySelected":false})
```

This is consistent with what "wmic" reports, but the number is wrong!

```
C:\Users\cad>wmic diskdrive list brief
Caption                           DeviceID            Model                             Partitions  Size
Samsung SSD 850 EVO 250GB         \\.\PHYSICALDRIVE0  Samsung SSD 850 EVO 250GB         3           250056737280
Multiple Card  Reader USB Device  \\.\PHYSICALDRIVE1  Multiple Card  Reader USB Device  1           7945620480
```

**Comment by rfjakob** [comment] 2017-05-19 09:31
Edit: Table was the wrong way round (Windows reports a smaller size). Corrected.

**Comment by lurch** [comment] 2017-05-19 12:59
Duplicate of https://github.com/resin-io-modules/drivelist/issues/142

At some point we're hoping to rewrite `drivelist` as a native C++ module, which will allow us to then use the "correct" (low-level) method of getting the SD card's size. Until then I'm afraid there's no workaround.

**Closed by lurch** 2017-05-19 12:59 UTC
