### ISSUE TITLE
Allow copy on a previously image drive

### ISSUE THREAD

**Issue by hayekr1** [resin-io/etcher#1036] opened 2017-01-19 23:07 UTC
There should be a way to take a previously imaged drive and copy it to another drive

**Comment by lurch** [comment] 2017-01-20 01:23
Duplicate of #266 ?

**Comment by jviotti** [comment] 2017-01-20 16:38
> take a previously imaged drive

That's basically an ISO or IMG, as any other image Etcher supports.

**Closed by jviotti** 2017-01-20 16:38 UTC
