### ISSUE TITLE
Command failed writing .img to SD card of 32GB

### ISSUE THREAD

**Issue by bears34egc** [resin-io/etcher#1254] opened 2017-04-02 21:39 UTC
- **Etcher version:1.0.0 beta.19
- **Operating system and architecture:Windows 7 64bit
- **Do you see any meaningful error information on DevTools?**

![image](https://cloud.githubusercontent.com/assets/8006556/24591252/e7b49902-17c2-11e7-80b0-382cd3bc80ee.png)

I'm wondering if this error is related to the issue with FATFORMAT of 32GB or greater SD cards. As noted here in this link?
https://www.raspberrypi.org/documentation/installation/sdxc_formatting.md

**Comment by jviotti** [comment] 2017-04-03 02:00
Hey there!

Thanks for reporting this. The issue is that we've been using a third party Windows program to handle ejecting drives (RemoveDrive, as you can see on the dialog) which has some known rough edges.

We've been working hard to implement our own Windows ejection mechanism, and the PR landed on master today (https://github.com/resin-io/etcher/pull/1209).

I'm going to close this issue, given I believe its fixed already. You can try the following snapshot build if you don't want to wait until the next version:

- Standalone x64: https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-04-03/1.0.0-beta.19%2Bc5a711a/Etcher-1.0.0-beta.19%2Bc5a711a-win32-x64.zip
- Installer x64: https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-04-03/1.0.0-beta.19%2Bc5a711a/Etcher-1.0.0-beta.19%2Bc5a711a-win32-x64.exe
- Standalone x86: https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-04-03/1.0.0-beta.19%2Bc5a711a/Etcher-1.0.0-beta.19%2Bc5a711a-win32-x86.zip
- Installer x86: https://resin-nightly-downloads.s3.amazonaws.com/etcher/2017-04-03/1.0.0-beta.19%2Bc5a711a/Etcher-1.0.0-beta.19%2Bc5a711a-win32-x86.exe

See https://github.com/resin-io/etcher/issues/1177 for the original issue.

**Closed by jviotti** 2017-04-03 02:00 UTC
